// cl: /MD
// Each class is declared locally only so its deleting destructor is emitted;
// the complete destructor call resolves through that destructor's own row.
// Generated by build/mg/famgen.py (gdtor30): same-shape family members.

// ??_GTextureStatisticsStruct@@QAEPAXI@Z @0x118f30
class TextureStatisticsStruct { public: ~TextureStatisticsStruct(); };
void famgenDelete(TextureStatisticsStruct *p) { delete p; }

// ??_GDX8IndexBufferClass@@UAEPAXI@Z @0x139200
class DX8IndexBufferClass { public: __declspec(noinline) virtual ~DX8IndexBufferClass(); private: int m_famgen; };
DX8IndexBufferClass::~DX8IndexBufferClass() { m_famgen = 0; }
void famgenDelete(DX8IndexBufferClass *p) { delete p; }

// ??_GSortingIndexBufferClass@@UAEPAXI@Z @0x139220
class SortingIndexBufferClass { public: __declspec(noinline) virtual ~SortingIndexBufferClass(); private: int m_famgen; };
SortingIndexBufferClass::~SortingIndexBufferClass() { m_famgen = 0; }
void famgenDelete(SortingIndexBufferClass *p) { delete p; }

// ??_GBfmeOwnVVE@@QAEPAXI@Z @0x15d020
class BfmeOwnVVE { public: ~BfmeOwnVVE(); };
void famgenDelete(BfmeOwnVVE *p) { delete p; }

// ??_GRva00180EA0@@UAEPAXI@Z @0x180e80
class Rva00180EA0 { public: __declspec(noinline) virtual ~Rva00180EA0(); private: int m_famgen; };
Rva00180EA0::~Rva00180EA0() { m_famgen = 0; }
void famgenDelete(Rva00180EA0 *p) { delete p; }

// ??_GGen_dtor_009f2600@@UAEPAXI@Z @0x6252d0
class Gen_dtor_009f2600 { public: __declspec(noinline) virtual ~Gen_dtor_009f2600(); private: int m_famgen; };
Gen_dtor_009f2600::~Gen_dtor_009f2600() { m_famgen = 0; }
void famgenDelete(Gen_dtor_009f2600 *p) { delete p; }

// ??_GRva00666BA0@@UAEPAXI@Z @0x661330
class Rva00666BA0 { public: __declspec(noinline) virtual ~Rva00666BA0(); private: int m_famgen; };
Rva00666BA0::~Rva00666BA0() { m_famgen = 0; }
void famgenDelete(Rva00666BA0 *p) { delete p; }

// ??_GGen_008AC620@@QAEPAXI@Z @0x6efb70
class Gen_008AC620 { public: ~Gen_008AC620(); };
void famgenDelete(Gen_008AC620 *p) { delete p; }
