// cl: /O1 /GX /MD /D_CRTIMP= /D_STLP_USE_STATIC_LIB /Ireference/shims/bfmealloc
// stlport
#include <vector>
// Generated by build/mg/famgen.py (vecdtor): same-shape family members.

// ??1?$vector@URva003F610FElement@@V?$allocator@URva003F610FElement@@@_STL@@@_STL@@QAE@XZ @0x3f5e85
struct Rva003F610FElement { public: ~Rva003F610FElement(); };
template _STL::vector<Rva003F610FElement>::~vector();

// ??1?$vector@URva004DA181Element@@V?$allocator@URva004DA181Element@@@_STL@@@_STL@@QAE@XZ @0x4d9f7a
struct Rva004DA181Element { public: ~Rva004DA181Element(); };
template _STL::vector<Rva004DA181Element>::~vector();

// ??1?$vector@URva00520211Element@@V?$allocator@URva00520211Element@@@_STL@@@_STL@@QAE@XZ @0x52012b
struct Rva00520211Element { public: ~Rva00520211Element(); };
template _STL::vector<Rva00520211Element>::~vector();
