// cl: /MD /D_STLP_NO_EXCEPTIONS /D_CRTIMP= /D_STLP_USE_STATIC_LIB /Ireference/shims/bfmealloc
// stlport
#include <vector>
// Generated by build/mg/famgen.py (vecchain): vector<T> dtors and their
// _Destroy range helpers; each element type wraps the destructor retail calls.

// @0xcf60b / _Destroy @0x48ce25
class CameraMarker { public: ~CameraMarker(); char m_pad[8]; };
template _STL::vector<CameraMarker>::~vector();

// @0x1d9ce5 / _Destroy @0x1d9ccc
class BfmeStringTailRecord156 { public: ~BfmeStringTailRecord156(); char m_pad[8]; };
template _STL::vector<BfmeStringTailRecord156>::~vector();

// @0x35b825 / _Destroy @0x31bdee
class Rva002390CB { public: ~Rva002390CB(); char m_pad[8]; };
template _STL::vector<Rva002390CB>::~vector();

// @0x569da2 / _Destroy @0x569a74
class BfmePoolRef10 { public: ~BfmePoolRef10(); char m_pad[12]; };
template _STL::vector<BfmePoolRef10>::~vector();

// @0x569d63 / _Destroy @0x569a5b
struct BfmeStringRecord00568CE0 { ~BfmeStringRecord00568CE0(); char m_pad[20]; };
template _STL::vector<BfmeStringRecord00568CE0>::~vector();

// _Destroy @0x297360 (no vector-dtor home: retail callers are manual destroys,
// not a vector dtor, so the vector emission stays unclaimed)
class Rva00297360Element { public: ~Rva00297360Element(); char m_pad[16]; };
template _STL::vector<Rva00297360Element>::~vector();

// _M_clear bodies (byte-identical explicit member instantiations calling
// each element's rowed _Destroy and _free): BfmeStringTailRecord156 at
// retail 0x001D9D57, Rva002390CB at 0x0031C81A, Rva00297360Element at
// 0x0040399F.
template void _STL::vector<BfmeStringTailRecord156>::_M_clear();
template void _STL::vector<Rva002390CB>::_M_clear();
template void _STL::vector<Rva00297360Element>::_M_clear();

// Keep this inlined unsigned max overload local; retail has one external owner.
// The construction specialization is owned by stlport_construct_throw_spec.cpp.
#pragma optimize("t", on)
namespace _STL {
static inline const unsigned int &max(
    const unsigned int &x, const unsigned int &y)
{
    return x < y ? y : x;
}

template <> void _Construct<Rva002390CB, Rva002390CB>(Rva002390CB *, const Rva002390CB &);
}
#pragma optimize("s", on)
// Explicit members avoid unrelated incompatible whole-class COMDAT copies.
template void _STL::vector<Rva002390CB, _STL::allocator<Rva002390CB> >::push_back(const Rva002390CB &);

// Callers elsewhere reach bodies in this unit through other spellings; retail's
// call sites in their matched rows land on these addresses (same ABI). Bind them.
#pragma comment(linker, "/alternatename:??1CameraMarkerVec@@QAE@XZ=??1?$vector@VCameraMarker@@V?$allocator@VCameraMarker@@@_STL@@@_STL@@QAE@XZ")
#pragma comment(linker, "/alternatename:??1W3DStreakWeatherVec@@QAE@XZ=??1?$vector@VCameraMarker@@V?$allocator@VCameraMarker@@@_STL@@@_STL@@QAE@XZ")

// Retail 0x0031BD77 is the 45-byte no-EH allocation-and-copy helper, not
// the insert candidate served by structural drift. Native calls identify the
// rowed 8-byte allocator at 0x00523D6C and const-range copy worker at
// 0x003399AD. Rva002390CB remains an opaque, address-qualified element view;
// its original class identity is not established. Stock STLport supplies the
// body; /D_STLP_NO_EXCEPTIONS matches the native absence of an EH frame.
template Rva002390CB * _STL::vector<Rva002390CB, _STL::allocator<Rva002390CB> >::_M_allocate_and_copy<const Rva002390CB *>(unsigned int, const Rva002390CB *, const Rva002390CB *);
