// Coord3D: canonical layout, generated by tools/header_adopt_lane.py from
// reverse/class_contracts/Coord3D.json (variant data+methods). Edit the contract, not this file.
// sizeof 12 (zh); class-key struct (bytes).
#ifndef CANONICAL_COORD3D_H
#define CANONICAL_COORD3D_H

struct Coord3D {
    float x;
    float y;
    float z;
    float length() const;
    void normalize();
    bool operator==(const Coord3D &r);
    float GetLengthSqrd() const;
    float GetLength() const;
    // Native 0x000037D1/108; existing coord3d.cpp owner and mux callers.
    float GetLengthEstimate2D() const;
    float GetLength2D() const;
    float Normalize();
    float operator*(const struct Coord3DBase &r) const;
};

#endif // CANONICAL_COORD3D_H
