// Coord3D: canonical layout, generated by tools/header_adopt_lane.py from
// reverse/class_contracts/Coord3D.json (variant data+methods). Edit the contract, not this file.
// sizeof 12 (zh); class-key struct (bytes).
#ifndef CANONICAL_COORD3D_H
#define CANONICAL_COORD3D_H

struct Coord3D {
    float x;
    float y;
    float z;
    float length() const;
    void normalize();
};

#endif // CANONICAL_COORD3D_H
