// Coord3D: canonical layout, generated by tools/header_adopt_lane.py from
// reverse/class_contracts/Coord3D.json (variant data+methods). Edit the contract, not this file.
// sizeof 12 (zh); class-key struct (bytes).
#ifndef CANONICAL_COORD3D_H
#define CANONICAL_COORD3D_H

struct Coord3D {
    float x;
    float y;
    float z;
    float length() const;
    void normalize();
    bool operator==(const Coord3D &r);
    float GetLengthSqrd() const;
    float GetLength() const;
    // Native 0x000037D1/108; existing coord3d.cpp owner and mux callers.
    float GetLengthEstimate2D() const;
    float GetLength2D() const;
    float Normalize();
    float operator*(const struct Coord3DBase &r) const;
    // Byte-verified owners in coord3d.cpp/region.cpp (0x366B, 0x36AE, 0xDFCB6, 0x36D1, 0x3702).
    // Coord3DBase arguments need Lib/Coord3DBase.h; it is not defined here (see that header).
    void zero();
    void set(float x, float y, float z);
    void set(const struct Coord3DBase *p);
    void scale(float s);
    bool equals(const struct Coord3DBase &that) const;
};

#endif // CANONICAL_COORD3D_H
