// Coord2D: canonical layout, generated by tools/header_adopt_lane.py from
// reverse/class_contracts/Coord2D.json (variant data+methods). Edit the contract, not this file.
// sizeof 8 (zh); class-key class (bytes).
#ifndef CANONICAL_COORD2D_H
#define CANONICAL_COORD2D_H

class Coord2D {
public:
    float x;
    float y;
    void normalize();
};

#endif // CANONICAL_COORD2D_H
