// ?rva00102F83@W3DCamTransform@@QAEXPAUCameraTransformInput@@@Z
// partial score=0.7944 date=2026-10-10
// cl: /I. /Ireference/shims/bfme2_ascii /O1 /G7 /arch:SSE /DNDEBUG /MD /ICode/Libraries/Include/Lib
//
// W3DCamTransform::transitionLiveMode
// ?transitionLiveMode@W3DCamTransform@@QAEXPAVVector3@@0PAVView@@@Z
// retail 0x00102B83..0x00102F83 (1024B), thiscall ret 0xC; sole caller is the
// W3DView camera update near 0x00103A6F, which passes the view as the third
// argument.
//
// Live-camera transition state machine (state at +0x28, target at +0x2C and
// position at +0x38). The current live mode name (global AsciiString
// 0x00DEC290) selects "Target" (2) or "Zoom" (3). Losing the controlled object
// (view +0xA4) resets the timers and the state. State 2 eases the target
// towards the object with an accelerating zoom timer, state 3 eases both target
// and position (after a screen-centre terrain query on TheTacticalView) and
// states 0, 1 and 4 hand over between them; reaching state 3 in the requested
// mode sets the view's +0xB4 / +0xB8 pair to 16 / 2.
//
// Evidence (target): WorldBuilder twin 0x7E73D0 is
// W3DCamTransform::transitionLiveMode in W3DCamTransform.cpp (asserts
// "W3DView-TransitionLiveCamera - no controlled object" at lines 529 and 569)
// and inlines Vector3::Lerp; two guarded static Vector3s (the second unused in
// retail), four zero-initialised static timers and four tuning statics
// (0.5 / 0.05 and 0.4 / 0.03). Callees StringBase::compare(text) 0x000069B1 and
// GameLogic::findObjectByID 0x00049DC5 (rowed).
//
// Shape note: the reset's self-select store of targetT (this ? 0 : 0) is what
// gives cl retail's register colouring of the cached zoom/target speeds
// (xmm1/xmm2) and its store order; every plainer spelling swaps the two.

#include "ascii_string.h"
// Coord3D: canonical layout, generated by tools/header_adopt_lane.py from
// reverse/class_contracts/Coord3D.json (variant data+methods). Edit the contract, not this file.
// sizeof 12 (zh); class-key struct (bytes).
#ifndef CANONICAL_COORD3D_H
#define CANONICAL_COORD3D_H

struct Coord3D {
    float x;
    float y;
    float z;
    float lengthSqr() const; // Existing owner 0x00065A1A, absent from canonical header.
    float length() const;
    void normalize();
    bool operator==(const Coord3D &r);
    float GetLengthSqrd() const;
    float GetLength() const;
    // Native 0x000037D1/108; existing coord3d.cpp owner and mux callers.
    float GetLengthEstimate2D() const;
    float GetLength2D() const;
    float Normalize();
    float operator*(const struct Coord3DBase &r) const;
    // Byte-verified owners in coord3d.cpp/region.cpp (0x366B, 0x36AE, 0xDFCB6, 0x36D1, 0x3702).
    // Coord3DBase arguments need Lib/Coord3DBase.h; it is not defined here (see that header).
    void zero();
    void set(float x, float y, float z);
    void set(const struct Coord3DBase *p);
    void scale(float s);
    bool equals(const struct Coord3DBase &that) const;
    // Native 0x00003ACE/372; nearest-template caller 0x00397429.
    float GetLengthEstimate() const;
};

#endif // CANONICAL_COORD3D_H

#include "Code/GameEngine/Source/Common/GameLogicObjectLookupView.h"

typedef int Int;
typedef bool Bool;
typedef float Real;

struct ICoord2D
{
	Int x;
	Int y;
};

class Vector3
{
public:
	Real X;
	Real Y;
	Real Z;

	Vector3() {}
    Vector3(float x,float y,float z):X(x),Y(y),Z(z) {}
	Vector3(const Vector3 &v)
	{
		X = v.X;
		Y = v.Y;
		Z = v.Z;
	}

	Vector3 &operator=(const Vector3 &v)
	{
		X = v.X;
		Y = v.Y;
		Z = v.Z;
		return *this;
	}

	void Set(Real x, Real y, Real z)
	{
		X = x;
		Y = y;
		Z = z;
	}

	static __forceinline void Lerp(const Vector3 &a, const Vector3 &b, Real alpha, Vector3 *set_result)
	{
		set_result->X = (a.X + (b.X - a.X) * alpha);
		set_result->Y = (a.Y + (b.Y - a.Y) * alpha);
		set_result->Z = (a.Z + (b.Z - a.Z) * alpha);
	}
};

class Object
{
public:
	const Coord3D *getPosition() const { return &m_pos; }
    unsigned char cameraKindFlags() const {return *((const unsigned char*)m_template+0x109);}
private:
	unsigned char m_pad00[4];
    const void *m_template; // native +4
    unsigned char m_pad08[0x38-8];
	Coord3D m_pos;					// +0x38
};

#define PAD_VIRTUALS10(p) \
	virtual void p##0(); virtual void p##1(); virtual void p##2(); virtual void p##3(); virtual void p##4(); \
	virtual void p##5(); virtual void p##6(); virtual void p##7(); virtual void p##8(); virtual void p##9();

class View
{
public:
	PAD_VIRTUALS10(v0) PAD_VIRTUALS10(v1) PAD_VIRTUALS10(v2) PAD_VIRTUALS10(v3) PAD_VIRTUALS10(v4)
	PAD_VIRTUALS10(v5) PAD_VIRTUALS10(v6) PAD_VIRTUALS10(v7) PAD_VIRTUALS10(v8)
	virtual void screenToTerrain(const ICoord2D *pixel, Coord3D *world, bool clamp);	// slot 90

	unsigned char m_pad004[0x9C - 0x04];
	Bool m_9c;					// +0x9C
	unsigned char m_pad09d[0xA4 - 0x9D];
	ObjectID m_cameraLock;				// +0xA4
	unsigned char m_pad0a8[0xB4 - 0xA8];
	Int m_b4;					// +0xB4
	Int m_b8;					// +0xB8
	Int m_width;					// +0xBC
	Int m_height;					// +0xC0
};

extern View *TheTacticalView;
extern GameLogic *TheGameLogic;
extern unsigned int g_Va00DEC290;	// live camera mode name (AsciiString)

#include <math.h>
// Reduced donor math view: formulas from GeneralsMD WWMath/matrix3d.h.
class Vector4 {
public:
    float X,Y,Z,W;
    Vector4() {}
    float &operator[](int i) {return (&X)[i];}
    const float &operator[](int i)const {return (&X)[i];}
};
class Matrix3D {
public:
    Vector4 Row[3];
    Matrix3D() {}
    explicit Matrix3D(bool init) {if(init)Make_Identity();}
    __forceinline Matrix3D(const Vector3 &a, float angle) {
        float c = (float)cos(angle), s = (float)sin(angle);
        float x=a.X,y=a.Y,z=a.Z;
        Row[0][0]=x*x+c*(1.0f-x*x); Row[0][1]=x*y*(1.0f-c)-z*s; Row[0][2]=z*x*(1.0f-c)+y*s; Row[0][3]=0;
        Row[1][0]=x*y*(1.0f-c)+z*s; Row[1][1]=y*y+c*(1.0f-y*y); Row[1][2]=y*z*(1.0f-c)-x*s; Row[1][3]=0;
        Row[2][0]=z*x*(1.0f-c)-y*s; Row[2][1]=y*z*(1.0f-c)+x*s; Row[2][2]=z*z+c*(1.0f-z*z); Row[2][3]=0;
    }
    __forceinline Matrix3D &operator=(const Matrix3D &m) {
        Row[0][0]=m.Row[0][0];
        Row[0][1]=m.Row[0][1];
        Row[0][2]=m.Row[0][2];
        Row[0][3]=m.Row[0][3];
        Row[1][0]=m.Row[1][0];
        Row[1][1]=m.Row[1][1];
        Row[1][2]=m.Row[1][2];
        Row[1][3]=m.Row[1][3];
        Row[2][0]=m.Row[2][0];
        Row[2][1]=m.Row[2][1];
        Row[2][2]=m.Row[2][2];
        Row[2][3]=m.Row[2][3];
        return *this;
    }
    __forceinline void Make_Identity() {
        Row[0][0]=1; Row[0][1]=0; Row[0][2]=0; Row[0][3]=0;
        Row[1][0]=0; Row[1][1]=1; Row[1][2]=0; Row[1][3]=0;
        Row[2][0]=0; Row[2][1]=0; Row[2][2]=1; Row[2][3]=0;
    }
    void Look_At(const Vector3 &,const Vector3 &,float);
    __forceinline void mulVector3(Vector3 &v) const {
        float x=Row[0][0]*v.X+Row[0][1]*v.Y+Row[0][2]*v.Z+Row[0][3];
        float y=Row[1][0]*v.X+Row[1][1]*v.Y+Row[1][2]*v.Z+Row[1][3];
        float z=Row[2][0]*v.X+Row[2][1]*v.Y+Row[2][2]*v.Z+Row[2][3];
        v.Set(x,y,z);
    }
    __forceinline void Rotate_X(float theta) {
        float s=(float)sin(theta),c=(float)cos(theta);
        {float a=Row[0][1],b=Row[0][2]; Row[0][1]=c*a+s*b;Row[0][2]=-s*a+c*b;}
        {float a=Row[1][1],b=Row[1][2]; Row[1][1]=c*a+s*b;Row[1][2]=-s*a+c*b;}
        {float a=Row[2][1],b=Row[2][2]; Row[2][1]=c*a+s*b;Row[2][2]=-s*a+c*b;}
    }
    __forceinline void Rotate_Y(float theta) {
        float s=(float)sin(theta),c=(float)cos(theta);
        {float a=Row[0][0],b=Row[0][2]; Row[0][0]=c*a-s*b;Row[0][2]=s*a+c*b;}
        {float a=Row[1][0],b=Row[1][2]; Row[1][0]=c*a-s*b;Row[1][2]=s*a+c*b;}
        {float a=Row[2][0],b=Row[2][2]; Row[2][0]=c*a-s*b;Row[2][2]=s*a+c*b;}
    }
    __forceinline void Rotate_Z(float theta) {
        float c=(float)cos(theta),s=(float)sin(theta);
        {float a=Row[0][0],b=Row[0][1]; Row[0][0]=c*a+s*b;Row[0][1]=-s*a+c*b;}
        {float a=Row[1][0],b=Row[1][1]; Row[1][0]=c*a+s*b;Row[1][1]=-s*a+c*b;}
        {float a=Row[2][0],b=Row[2][1]; Row[2][0]=c*a+s*b;Row[2][1]=-s*a+c*b;}
    }
};
class CameraAnimation {public:virtual void slot0();virtual void slot1();virtual void getTransform(Matrix3D *);};
struct CameraTransformInput {
    Matrix3D *transform; float distance;
    Vector3 source,target,shakerAngles;
    float groundLevel,zoom,angle,pitch,roll,fov,finalRotation,targetZAdjustment;
    Coord3D pos,previousPos,explicitTarget;
    float shakeX,shakeY;
    bool constraintValid; char pad79[3];
    float minX,minY,maxX,maxY;
    bool realZoom; char pad8d[3]; Vector3 offset;
    bool liveCamera; char pad9d[3]; float fxPitch; ObjectID lock;
    bool positionHold,retainHold,slaved;char padab;
    AsciiString slaveName,boneName;
    char padb4[0xd0-0xb4]; bool special,padd1,nearAdjust,padd3;
    int mode; CameraAnimation *animation; float animationValue;
};
class CameraShakeSystemClass {public:void Update_Camera_Shaker(Vector3,Vector3 *);};
class Rva0065CA4 {public:void rva00065E3C(float);};
extern CameraShakeSystemClass CameraShakerSystem;
class Display {public:
    PAD_VIRTUALS10(d0) PAD_VIRTUALS10(d1) PAD_VIRTUALS10(d2) PAD_VIRTUALS10(d3)
    PAD_VIRTUALS10(d4) PAD_VIRTUALS10(d5) PAD_VIRTUALS10(d6) PAD_VIRTUALS10(d7)
    virtual void d80();virtual void d81();virtual void d82();virtual void d83();
    virtual void d84();virtual void d85();virtual void d86();virtual void d87();
    virtual bool isLetterBoxed();
};
extern Display *TheDisplay;
class ScriptEngine;
extern ScriptEngine *TheScriptEngine;
class Rva00358752Opaque {public:Object *lookupUnitByValue(AsciiString);};
class Rva002B224BDwordField {public:int get()const;};
class Drawable;
class Thing {public:Drawable *getDrawable() const;};
class ObjectDrawInterface {public:virtual void slot0();virtual void slot1();virtual bool boneTransform(const AsciiString &,Matrix3D *)const;};
class DrawModule {public:
    PAD_VIRTUALS10(dm0) PAD_VIRTUALS10(dm1) PAD_VIRTUALS10(dm2) PAD_VIRTUALS10(dm3)
    virtual void dm40();virtual void dm41();virtual const ObjectDrawInterface *getObjectDrawInterface()const;
};

class W3DCamTransform
{
public:
	void transitionLiveMode(Vector3 *pos, Vector3 *target, View *view);
    void rva00102F83(CameraTransformInput *);
private:
	unsigned char m_pad00[0x0c];
    Vector3 m_cameraSource; // +0x0c
    char m_pad18[2]; bool m_cameraFlag; // +0x1a
    char m_pad1b[0x28-0x1b];
	Int m_liveState;				// +0x28
	Vector3 m_liveTarget;				// +0x2C
	Vector3 m_livePos;				// +0x38
};

static __forceinline const AsciiString &liveModeName()
{
	return *(const AsciiString *)&g_Va00DEC290;
}

void W3DCamTransform::transitionLiveMode(Vector3 *pos, Vector3 *target, View *view)
{
	static Vector3 startPos;
	static Vector3 unusedPos;
	static Real zoomT = 0.0f;
	static Real zoomSpeed = 0.0f;
	static Real targetT = 0.0f;
	static Real targetSpeed = 0.0f;
	static Real targetMaxSpeed = 0.5f;
	static Real targetAccel = 0.05f;
	static Real zoomMaxSpeed = 0.4f;
	static Real zoomAccel = 0.03f;

	Int liveMode = -1;
	if (liveModeName().compare("Target") == 0)
		liveMode = 2;
	else if (liveModeName().compare("Zoom") == 0)
		liveMode = 3;

	Object *obj = TheGameLogic->findObjectByID(view->m_cameraLock);
	if (!obj)
	{
		zoomT = 0.0f;
		zoomSpeed = 0.0f;
		targetT = this ? 0.0f : 0.0f;
		targetSpeed = 0.0f;
		m_liveState = 0;
	}

	if (!view->m_9c)
	{
		m_liveTarget = *target;
		m_livePos = *pos;
	}

	switch (m_liveState)
	{
		case 0:
			if (view->m_9c)
			{
				m_liveState = 3;
				if (liveMode == m_liveState)
				{
					startPos = m_livePos;
					view->m_b4 = 16;
					view->m_b8 = 2;
				}
			}
			break;

		case 1:
			if (!view->m_9c)
				m_liveState = 4;
			break;

		case 2:
		{
			zoomT += zoomSpeed;
			if (zoomSpeed < zoomMaxSpeed)
				zoomSpeed += zoomAccel;

			Object *lockObj = TheGameLogic->findObjectByID(view->m_cameraLock);
			Vector3 objPos;
			objPos.Set(lockObj->getPosition()->x, lockObj->getPosition()->y, lockObj->getPosition()->z);
			Vector3::Lerp(m_liveTarget, objPos, zoomT, target);
			*pos = m_livePos;
			if (zoomT >= 1.0f)
			{
				m_liveState = 3;
				zoomT = 0.0f;
				zoomSpeed = 0.0f;
				startPos = m_livePos;
				if (liveMode == m_liveState)
				{
					view->m_b4 = 16;
					view->m_b8 = 2;
				}
			}
			break;
		}

		case 3:
		{
			Real maxSpeed = targetMaxSpeed;
			Real accel = targetAccel;
			targetT += targetSpeed;
			if (targetSpeed < maxSpeed)
				targetSpeed += accel;

			if (targetT < 0.9f)
			{
				Object *lockObj = TheGameLogic->findObjectByID(view->m_cameraLock);
				Vector3 objPos;
				objPos.Set(lockObj->getPosition()->x, lockObj->getPosition()->y, lockObj->getPosition()->z);
				Coord3D world;
				ICoord2D center;
				center.x = view->m_width / 2;
				center.y = view->m_height / 2;
				TheTacticalView->screenToTerrain(&center, &world, false);
				Vector3::Lerp(m_liveTarget, objPos, targetT, target);
				Vector3::Lerp(startPos, m_liveTarget, targetT, pos);
			}
			else
			{
				m_liveState = 1;
				targetT = 0.0f;
				targetSpeed = 0.0f;
				view->m_b4 = 0;
				view->m_b8 = 0;
			}
			break;
		}

		case 4:
			m_liveState = 0;
			break;
	}
}

// Whole native 0x00102F83..0x0010404E, 4299 bytes, RET4.
// Identity: enclosing W3DCamTransform and reference camera algorithm;
// original entry-point/descriptor names are not independently established.
void W3DCamTransform::rva00102F83(CameraTransformInput *v)
{
    Vector3 sourcePos,targetPos;
    if(v->mode==4) {
        if(v->animation) {
            struct AnimatedTransform {Matrix3D tm;float value;} result;
            v->animation->getTransform(&result.tm);
            *v->transform=result.tm; v->animationValue=result.value; return;
        }
        v->mode=0;
    }
    v->pos.x+=v->shakeX;v->pos.y+=v->shakeY;
    if(v->mode==2) {
        sourcePos.Set(v->pos.x,v->pos.y,v->pos.z);
        if(v->explicitTarget.lengthSqr()==0.0f) targetPos.Set(v->pos.x,v->pos.y,0);
        else targetPos.Set(v->explicitTarget.x,v->explicitTarget.y,v->explicitTarget.z);
        v->transform->Make_Identity();v->transform->Look_At(sourcePos,targetPos,v->roll); return;
    }
    if(v->constraintValid) {
        v->pos.x=v->minX>v->pos.x?v->minX:v->pos.x;
        v->pos.x=v->maxX<v->pos.x?v->maxX:v->pos.x;
        v->pos.y=v->minY>v->pos.y?v->minY:v->pos.y;
        v->pos.y=v->maxY<v->pos.y?v->maxY:v->pos.y;
    }
    if(v->realZoom) {
        sourcePos=v->offset;
        float capped=v->zoom;
        if(capped>1.0f)capped=1.0f;
        if(capped<0.5f)capped=0.5f;
        v->fov=0.87266463f*capped;
    } else {
        sourcePos.Set(v->offset.X*v->zoom,v->offset.Y*v->zoom,v->offset.Z*v->zoom);
        if(v->liveCamera) {
            Object *object=TheGameLogic->findObjectByID(v->lock);
            if(object) sourcePos.Z=(v->offset.Z+object->getPosition()->z)*v->zoom;
        }
    }
    targetPos.Set(0,0,0);
    float factor=1.0-(v->groundLevel/sourcePos.Z);
    Matrix3D angleTransform(Vector3(0,0,1),v->angle);
    Matrix3D pitchTransform(Vector3(1,0,0),v->pitch);
    pitchTransform.mulVector3(sourcePos); angleTransform.mulVector3(sourcePos);
    sourcePos.X*=factor;sourcePos.Y*=factor;sourcePos.Z*=factor;
    sourcePos.X+=v->pos.x;sourcePos.Y+=v->pos.y;
    targetPos.X+=v->pos.x;targetPos.Y+=v->pos.y;
    Object *object=v->liveCamera?TheGameLogic->findObjectByID(v->lock):0;
    if(v->liveCamera && (!object || (object->cameraKindFlags()&0x10))) {
        Matrix3D angleTransform2(Vector3(0,0,1),v->angle);
        Matrix3D pitchTransform2(Vector3(1,0,0),v->pitch);
        pitchTransform2.mulVector3(sourcePos);angleTransform2.mulVector3(sourcePos);
        sourcePos.X+=v->pos.x;sourcePos.Y+=v->pos.y;sourcePos.Z+=v->pos.z;
        targetPos.X+=v->pos.x;targetPos.Y+=v->pos.y;targetPos.Z+=v->pos.z+v->targetZAdjustment;
    } else {
        sourcePos.Z+=v->groundLevel;
        targetPos.Z+=v->groundLevel+v->targetZAdjustment;
    }
    if(v->realZoom) {
        float pitchAdjust=1.0f;
        if(!TheDisplay->isLetterBoxed()) {
            float capped=v->zoom;
            if(capped>1.0f)capped=1.0f;
            if(capped<0.5f)capped=0.5f;
            sourcePos.Z*=capped*0.75f+0.25f; pitchAdjust=capped;
        }
        v->fxPitch=1.0f*(0.25f+pitchAdjust*0.75f);
        float inversePitch=1.0f/v->fxPitch;
        sourcePos.X=targetPos.X+(sourcePos.X-targetPos.X)*inversePitch;
        sourcePos.Y=targetPos.Y+(sourcePos.Y-targetPos.Y)*inversePitch;
    } else if(v->liveCamera) {
        if(m_cameraFlag)m_cameraFlag=false;
        m_cameraSource=sourcePos;
        float dx=targetPos.X-sourcePos.X,dy=targetPos.Y-sourcePos.Y;
        float distance=(float)sqrt(dx*dx+dy*dy);
        targetPos.Z=sourcePos.Z-tan(v->fxPitch)*distance;
        float inversePitch=1.0f/v->fxPitch;
        sourcePos.X=targetPos.X+(sourcePos.X-targetPos.X)*inversePitch;
        sourcePos.Y=targetPos.Y+(sourcePos.Y-targetPos.Y)*inversePitch;
    } else if(v->fxPitch<=1.0f) {
        float height=sourcePos.Z-targetPos.Z; height*=v->fxPitch;targetPos.Z=sourcePos.Z-height;
    } else {
        float inversePitch=1.0f/v->fxPitch;
        sourcePos.X=targetPos.X+(sourcePos.X-targetPos.X)*inversePitch;
        sourcePos.Y=targetPos.Y+(sourcePos.Y-targetPos.Y)*inversePitch;
    }
    if(v->positionHold) {
        Vector3 delta(v->source.X-sourcePos.X,v->source.Y-sourcePos.Y,v->source.Z-sourcePos.Z);
        sourcePos=v->source;
        targetPos.X+=delta.X;targetPos.Y+=delta.Y;targetPos.Z+=delta.Z;
        v->pos=v->previousPos;v->pos.x+=delta.X;v->pos.y+=delta.Y;v->previousPos=v->pos;
        if(!v->retainHold)v->positionHold=false;
    }
    v->source=sourcePos;v->target=targetPos;
    float dx=v->source.X-v->target.X,dy=v->source.Y-v->target.Y,dz=v->source.Z-v->target.Z;
    v->distance=(float)sqrt(dx*dx+dz*dz+dy*dy);
    if(!v->special) transitionLiveMode(&sourcePos,&targetPos,(View*)v);
    if(v->explicitTarget.lengthSqr()>0)targetPos.Set(v->explicitTarget.x,v->explicitTarget.y,v->explicitTarget.z);
    v->transform->Make_Identity();v->transform->Look_At(sourcePos,targetPos,v->roll);
    if(!v->special) {
        CameraShakeSystemClass *system=*(CameraShakeSystemClass**)&CameraShakerSystem;
        ((Rva0065CA4 *)system)->rva00065E3C(1.0f/30.0f);
        system->Update_Camera_Shaker(sourcePos,&v->shakerAngles);
        v->transform->Rotate_X(v->shakerAngles.X);
        v->transform->Rotate_Y(v->shakerAngles.Y);
        v->transform->Rotate_Z(v->shakerAngles.Z);
    }
    if(v->slaved) {
        Object *slave=((Rva00358752Opaque*)TheScriptEngine)->lookupUnitByValue(v->slaveName);
        if(slave) {
            Drawable *draw=((Thing*)slave)->getDrawable();
            if(draw) {
                DrawModule **modules=(DrawModule**)((Rva002B224BDwordField*)draw)->get();
                for(;*modules;++modules) {
                    const ObjectDrawInterface *di=(*modules)->getObjectDrawInterface();
                    if(di) {
                        Matrix3D tm(false);di->boneTransform(v->boneName,&tm);*v->transform=tm;
                        v->previousPos.x=v->transform->Row[0][3];
                        v->previousPos.y=v->transform->Row[1][3];
                        v->previousPos.z=v->transform->Row[2][3]; break;
                    }
                }
            } else v->slaved=false;
        } else v->slaved=false;
    }
    v->transform->Rotate_Y(v->finalRotation);
    if(v->special&&v->nearAdjust) {
        sourcePos.X=targetPos.X+(sourcePos.X-targetPos.X)/(90.0f+v->fxPitch);
        sourcePos.Y=targetPos.Y+(sourcePos.Y-targetPos.Y)/(90.0f+v->fxPitch);
        v->transform->Look_At(sourcePos,targetPos,0);
        v->source=sourcePos;v->target=targetPos;
    }
}
