// ?rva004BB176@HordeTransportContainDamage@@UAEXPAVDamageInfo@@@Z
// partial score=0.892833252218575 date=2026-10-10
// cl: /O1 /G7 /arch:SSE /MD /EHsc /DNDEBUG /D_CRTIMP= /D_STLP_USE_STATIC_LIB /D_STLP_NO_EXCEPTIONS /Ireference/shims/bfmealloc /I.
// stlport
// Complete native4BB176..4BB391 RET4 (539B). Address-derived damage callback.
// Target identity: named factory250E9C allocates20B and calls ctor4BB130;
// ctor installs secondary damage vtableC59E64 at+10, slot0 VA8BB176.
// Secondary receiver accesses owner at-8. Every field and numbered virtual
// slot below is witnessed in this callback; no full class layout is claimed.
// ZH TransportContain provides the container/contained-object relationship;
// target horde damage redistribution is a BFME-specific extension. No donor
// name, inherited layout, or success enum is inferred from matching bytes.
#include <list>
namespace _STL {
template<> __declspec(noinline) list<int>::_Node *list<int>::_M_create_node(const int &x) {
 _Node *p=this->_M_node.allocate(1);_Construct(&p->_M_data,x);return p;
}
template<> __declspec(noinline) list<int>::iterator list<int>::insert(list<int>::iterator pos,const int &x) {
 _Node *tmp=_M_create_node(x);_List_node_base *n=pos._M_node,*p=n->_M_prev;
 tmp->_M_next=n;tmp->_M_prev=p;p->_M_next=tmp;n->_M_prev=tmp;return tmp;
}
}
#include "Code/GameEngine/Source/Common/GameLogicObjectLookupView.h"
extern GameLogic *TheGameLogic;
enum DamageType { NATIVE_DAMAGE8=8 };enum DeathType { NATIVE_DEATH0=0 };
class Object {public:void kill(DamageType,DeathType);};
class DamageInfo;
struct DamageInfoView {char prefix[0x74];float damage;};
class HordeCountView;class HordePayloadView;
struct DamageNode {DamageNode *next,*prev;Object *object;};
struct DamageListHeader {DamageNode *head;};
struct DamageListOutput {unsigned state;std::list<Object*> *list;};
class DamageBodyView {public:virtual void s0();virtual void s1();virtual void s2();virtual void s3();virtual float s4();virtual void s5();virtual float s6();};
class DamageContainView {public:
 virtual void s0();
 virtual void s1();
 virtual void s2();
 virtual void s3();
 virtual void s4();
 virtual void s5();
 virtual void s6();
 virtual void s7();
 virtual void s8();
 virtual void s9();
 virtual void s10();
 virtual void s11();
 virtual void s12();
 virtual void s13();
 virtual void s14();
 virtual void s15();
 virtual void s16();
 virtual void s17();
 virtual void s18();
 virtual void s19();
 virtual void s20();
 virtual void s21();
 virtual void s22();
 virtual void s23();
 virtual void s24();
 virtual void s25();
 virtual void s26();
 virtual void s27();
 virtual void s28();
 virtual void s29();
 virtual void s30();
 virtual HordePayloadView *s31();
 virtual void s32();
 virtual void s33();
 virtual void s34();
 virtual void s35();
 virtual void s36();
 virtual void s37();
 virtual void s38();
 virtual void s39();
 virtual void s40();
 virtual void s41();
 virtual void s42();
 virtual void s43();
 virtual void s44();
 virtual void s45();
 virtual void s46();
 virtual void s47();
 virtual void s48();
 virtual void s49();
 virtual void s50();
 virtual void s51();
 virtual void s52();
 virtual void s53();
 virtual void s54();
 virtual void s55();
 virtual void s56();
 virtual void s57();
 virtual void s58();
 virtual void s59();
 virtual void s60();
 virtual void s61();
 virtual void s62();
 virtual void s63();
 virtual void s64();
 virtual void s65();
 virtual void s66();
 virtual void s67();
 virtual void s68();
 virtual void s69();
 virtual void s70(DamageListOutput*);
};
class HordePayloadView {public:
 virtual void s0();
 virtual void s1();
 virtual void s2();
 virtual void s3();
 virtual void s4();
 virtual void s5();
 virtual void s6();
 virtual void s7();
 virtual void s8();
 virtual void s9();
 virtual void s10();
 virtual void s11();
 virtual void s12();
 virtual void s13();
 virtual void s14();
 virtual void s15();
 virtual void s16();
 virtual void s17();
 virtual void s18();
 virtual void s19();
 virtual void s20();
 virtual void s21();
 virtual void s22();
 virtual void s23();
 virtual void s24();
 virtual void s25();
 virtual void s26();
 virtual void s27();
 virtual void s28();
 virtual void s29();
 virtual void s30();
 virtual void s31();
 virtual void s32();
 virtual void s33();
 virtual void s34();
 virtual void s35();
 virtual void s36();
 virtual void s37();
 virtual void s38();
 virtual void s39();
 virtual void s40();
 virtual void s41();
 virtual void s42();
 virtual void s43();
 virtual void s44();
 virtual void s45();
 virtual void s46();
 virtual void s47();
 virtual void s48();
 virtual void s49();
 virtual void s50();
 virtual void s51();
 virtual void s52();
 virtual void s53();
 virtual void s54();
 virtual void s55();
 virtual void s56();
 virtual void s57();
 virtual void s58();
 virtual void s59();
 virtual void s60();
 virtual void s61();
 virtual void s62();
 virtual void s63();
 virtual void s64();
 virtual void s65();
 virtual void s66();
 virtual void s67();
 virtual void s68();
 virtual void s69();
 virtual void s70();
 virtual void s71();
 virtual void s72();
 virtual void s73();
 virtual void s74();
 virtual void s75();
 virtual void s76();
 virtual void s77();
 virtual void s78();
 virtual void s79();
 virtual void s80();
 virtual void s81();
 virtual void s82();
 virtual void s83();
 virtual void s84();
 virtual void s85();
 virtual void s86();
 virtual void s87();
 virtual void s88();
 virtual void s89();
 virtual void s90();
 virtual void s91();
 virtual void s92();
 virtual void s93();
 virtual void s94();
 virtual void s95();
 virtual void s96();
 virtual void s97();
 virtual void s98();
 virtual void s99();
 virtual void s100();
 virtual void s101();
 virtual void s102();
 virtual void s103();
 virtual void s104();
 virtual void s105();
 virtual void s106();
 virtual void s107();
 virtual void s108();
 virtual void s109();
 virtual void s110();
 virtual void s111();
 virtual void s112();
 virtual void s113();
 virtual void s114();
 virtual void s115();
 virtual void s116();
 virtual void s117();
 virtual void s118();
 virtual void s119();
 virtual void s120();
 virtual void s121();
 virtual void s122();
 virtual void s123();
 virtual void s124();
 virtual void s125();
 virtual void s126();
 virtual void s127();
 virtual void s128();
 virtual void s129();
 virtual void s130();
 virtual void s131();
 virtual void s132();
 virtual void s133();
 virtual HordeCountView *s134();
};
class HordeCountInterface {public:
 virtual void s0();
 virtual void s1();
 virtual void s2();
 virtual void s3();
 virtual void s4();
 virtual void s5();
 virtual void s6();
 virtual void s7();
 virtual void s8();
 virtual void s9();
 virtual void s10();
 virtual void s11();
 virtual void s12();
 virtual void s13();
 virtual void s14();
 virtual void s15();
 virtual void s16();
 virtual void s17();
 virtual void s18();
 virtual void s19();
 virtual void s20();
 virtual void s21();
 virtual void s22();
 virtual void s23();
 virtual void s24();
 virtual void s25();
 virtual void s26();
 virtual void s27();
 virtual void s28();
 virtual void s29();
 virtual void s30();
 virtual void s31();
 virtual void s32();
 virtual void s33();
 virtual void s34();
 virtual void s35();
 virtual void s36();
 virtual void s37();
 virtual void s38();
 virtual void s39();
 virtual void s40();
 virtual void s41();
 virtual void s42();
 virtual void s43();
 virtual void s44();
 virtual void s45();
 virtual void s46();
 virtual void s47();
 virtual void s48();
 virtual void s49();
 virtual void s50();
 virtual void s51();
 virtual void s52();
 virtual void s53();
 virtual void s54();
 virtual void s55();
 virtual void s56();
 virtual void s57();
 virtual void s58();
 virtual void s59();
 virtual void s60();
 virtual void s61();
 virtual void s62();
 virtual void s63();
 virtual void s64();
 virtual void s65();
 virtual void s66();
 virtual void s67();
 virtual void s68();
 virtual void s69();
 virtual void s70();
 virtual void s71();
 virtual void s72();
 virtual void s73();
 virtual void s74();
 virtual void s75();
 virtual void s76();
 virtual void s77();
 virtual void s78();
 virtual void s79();
 virtual void s80();
 virtual void s81();
 virtual void s82();
 virtual void s83();
 virtual void s84();
 virtual void s85();
 virtual void s86();
 virtual void s87();
 virtual void s88();
 virtual void s89();
 virtual void s90();
 virtual void s91();
 virtual void s92();
 virtual void s93();
 virtual void s94();
 virtual unsigned s95();virtual unsigned s96(bool);
};
struct HordeCountView {char head[0x20];DamageContainView contain;char toCount[0x11C-0x24];HordeCountInterface counts;};
struct DamageTemplateView {char head[0x115];unsigned char flag115;};
struct DamageObjectView {char head[4];DamageTemplateView *what;char rest[0x74-8];int id;char rest78[0x250-0x78];DamageContainView *contain;DamageBodyView *body;};
class HordeTransportContainDamage {public:virtual void rva004BB176(DamageInfo*);Object *getOwner()const{return *(Object*const*)((const char*)this-8);}};
void HordeTransportContainDamage::rva004BB176(DamageInfo *damage) {
 DamageBodyView *body=((DamageObjectView*)getOwner())->body;
 if(!body)return;
 float current=body->s4();float maximum=body->s6();
 float before=current+((DamageInfoView*)damage)->damage;
 if(!(maximum>before))before=maximum;
 DamageContainView *contain=((DamageObjectView*)getOwner())->contain;
 if(!contain)return;
 DamageListOutput outer;contain->s70(&outer);
 std::list<int> dead;
 std::list<Object*>::iterator it=outer.list->begin();
 while(it._M_node!=outer.list->end()._M_node) {
  Object *obj=*it++;
  if(!obj||!(((DamageObjectView*)obj)->what->flag115&0x20))continue;
  DamageContainView **cv=&((DamageObjectView*)obj)->contain;
  if(!*cv||!(*cv)->s31())continue;
  HordeCountView *horde=(*cv)->s31()->s134();HordeCountView *volatile saved=horde;if(!horde)continue;
  unsigned present=horde->counts.s96(false);if(present<=1)continue;
  unsigned limit=horde->counts.s95();if(!limit)continue;
  float ratio=1.0f/(maximum/(float)limit);
  unsigned oldCount=(unsigned)(int)(before*ratio)+1;if(oldCount>=limit)oldCount=limit;
  unsigned newCount=(unsigned)(int)(current*ratio)+1;if(newCount>=limit)newCount=limit;
  if(present<=newCount)continue;
  unsigned remove=oldCount-newCount;if(present-remove<newCount)remove=present-newCount;
  DamageListOutput inner;saved->contain.s70(&inner);
  std::list<Object*>::iterator victim=inner.list->begin();
  for(unsigned i=0;i<remove&&victim._M_node!=inner.list->end()._M_node;++i) {
   Object *obj=*victim++;
   if(obj) {int id=((DamageObjectView*)obj)->id;dead.push_back(id);}
  }
 }
 outer.state=0;
 for(std::list<int>::iterator i=dead.begin(),end=dead.end();i._M_node!=end._M_node;++i) {
  Object *obj=TheGameLogic->findObjectByID((ObjectID)*i);
  if(obj)obj->kill(NATIVE_DAMAGE8,NATIVE_DEATH0);
 }
}
