// ?rva0028BE93@Object@@QBE?AUCoord3D@@XZ
// partial score=1.0 date=2026-10-10
// BANK ONLY: exact correct by-value77 requires memberwise copy construction.
// The embedded Coord3D is a private proof of the proposed canonical contract,
// not an allowed production private view. Existing canonical header must be
// coherently reconciled with its dependent aggregate initializers before use.
// cl: /O1 /G7 /arch:SSE /Oy- /DNDEBUG /MD
//
// ?rva0028BE93@Object@@QBE?AUCoord3D@@XZ, retail 0x0028BE93, 77 bytes, hidden result ret 4.
// Copies a position into the caller's output and returns it: the Coord3D the member at +0x240
// writes through the rowed 0x0028A82A when that member exists, else a zeroed one.
// Evidence: target bytes and the rowed member call; the member's class and field are neutral.

// Coord3D: canonical layout, generated by tools/header_adopt_lane.py from
// reverse/class_contracts/Coord3D.json (variant data+methods). Edit the contract, not this file.
// sizeof 12 (zh); class-key struct (bytes).
#ifndef CANONICAL_COORD3D_H
#define CANONICAL_COORD3D_H

struct Coord3D {
    Coord3D() {}
    Coord3D(const Coord3D &r) : x(r.x), y(r.y), z(r.z) {}
    float x;
    float y;
    float z;
    float length() const;
    void normalize();
    bool operator==(const Coord3D &r);
    float GetLengthSqrd() const;
    float GetLength() const;
    // Native 0x000037D1/108; existing coord3d.cpp owner and mux callers.
    float GetLengthEstimate2D() const;
    float GetLength2D() const;
    float Normalize();
    float operator*(const struct Coord3DBase &r) const;
    // Byte-verified owners in coord3d.cpp/region.cpp (0x366B, 0x36AE, 0xDFCB6, 0x36D1, 0x3702).
    // Coord3DBase arguments need Lib/Coord3DBase.h; it is not defined here (see that header).
    void zero();
    void set(float x, float y, float z);
    void set(const struct Coord3DBase *p);
    void scale(float s);
    bool equals(const struct Coord3DBase &that) const;
    // Native 0x00003ACE/372; nearest-template caller 0x00397429.
    float GetLengthEstimate() const;
};

#endif // CANONICAL_COORD3D_H


class Rva0028AF76Sub
{
public:
	void *rva0028A82A(void *out) const;
};

class Object
{
public:
	Coord3D rva0028BE93() const;
private:
	char m_pad[0x240];
	Rva0028AF76Sub *m_sub240;
};

Coord3D Object::rva0028BE93() const
{
	struct { Coord3D tmp; Coord3D zero; int w; } l;
	l.w = 0;
	l.zero.x = 0.0f;
	l.zero.y = 0.0f;
	l.zero.z = 0.0f;
	const Coord3D *source;
	if (m_sub240)
		source = (const Coord3D *)m_sub240->rva0028A82A(&l.tmp);
	else
		source = &l.zero;
	return *source;
}
