// ?rva0020EA58@Rva002B2702B0@@QAE_NPAXPAM@Z
// partial score=0.95 date=2026-10-07
// cl: /O1 /arch:SSE /Ob1 /EHsc /MD
struct Rva0020E47CVal {float x,y; Rva0020E47CVal(const Rva0020E47CVal&a):x(a.x),y(a.y){} };
class Rva0020E47C {public:Rva0020E47CVal rva0020E47C();char pad[0x54];char*name;char pad58[0x28];Rva0020E47CVal value;char pad88;bool custom;};
Rva0020E47CVal Rva0020E47C::rva0020E47C(){return value;}
struct Region3D {Region3D(const Region3D&);float x_min,y_min,z_min,x_max,y_max,z_max;};
class PositionQueryObject {public:virtual void destroy();
 virtual void slot1();
 virtual void slot2();
 virtual void slot3();
 virtual void slot4();
 virtual void slot5();
 virtual void slot6();
 virtual void slot7();
 virtual void slot8();
 virtual void slot9();
 virtual void slot10();
 virtual void slot11();
 virtual void slot12();
 virtual void slot13();
 virtual void slot14();
 virtual void slot15();
 virtual void slot16();
 virtual void slot17();
 virtual void slot18();
 virtual void slot19();
 virtual void slot20();
 virtual void slot21();
 virtual void slot22();
 virtual void slot23();
 virtual void slot24();
 virtual void slot25();
 virtual void slot26();
 virtual void slot27();
 virtual void slot28();
 virtual void slot29();
 virtual void slot30();
 virtual void slot31();
 virtual void slot32();
 virtual void slot33();
 virtual void slot34();
 virtual void slot35();
 virtual void slot36();
 virtual void slot37();
 virtual void slot38();
 virtual void slot39();
 virtual void slot40();
 virtual void slot41();
 virtual void slot42();
 virtual void slot43();
 virtual void slot44();
 virtual void slot45();
 virtual void slot46();
 virtual void slot47();
 virtual void slot48();
 virtual void slot49();
 virtual void slot50();
 virtual void slot51();
 virtual void slot52();
 virtual void slot53();
 virtual void slot54();
 virtual void slot55();
 virtual void slot56();
 virtual void slot57();
 virtual void slot58();
 virtual void slot59();
 virtual void slot60();
 virtual void slot61();
 virtual void slot62();
 virtual void slot63();
 virtual void slot64();
 virtual void slot65();
 virtual const Region3D* bounds();int references;};
class PositionQueryFactory {public:
 virtual void slot0();
 virtual void slot1();
 virtual void slot2();
 virtual void slot3();
 virtual void slot4();
 virtual void slot5();
 virtual void slot6();
 virtual void slot7();
 virtual void slot8();
 virtual void slot9();
 virtual void slot10();
 virtual void slot11();
 virtual void slot12();
 virtual void slot13();
 virtual void slot14();
 virtual void slot15();
 virtual void slot16();
 virtual void slot17();
 virtual void slot18();
 virtual void slot19();
 virtual void slot20();
 virtual void slot21();
 virtual void slot22();
 virtual void slot23();
 virtual void slot24();
 virtual void slot25();
 virtual void slot26();
 virtual void slot27();
 virtual void slot28();
 virtual void slot29();
 virtual void slot30();
 virtual void slot31();
virtual PositionQueryObject*create(const char*,int);};
struct PositionQueryCampaign {char pad[4];PositionQueryFactory*factory;};
class Rva00DFE1C8Host {public:char pad[0x268];PositionQueryCampaign *campaign;};
extern Rva00DFE1C8Host*g_00DFE1C8;
class Rva002B2702B0 {public:bool rva0020EA58(void*key,float*out);};
bool Rva002B2702B0::rva0020EA58(void*key,float*out){
 Rva0020E47C*region=(Rva0020E47C*)key;
 if(region->custom){*(Rva0020E47CVal*)out=region->rva0020E47C();return true;}
 PositionQueryFactory *factory=g_00DFE1C8->campaign->factory;
 const char*name=region->name ? region->name+8 : "";
 PositionQueryObject*object=factory->create(name,0);
 if(!object)return false;
 Region3D bounds(*object->bounds());
 out[0]=bounds.x_min;out[1]=bounds.y_min;
 if(--object->references==0)object->destroy();
 return true;
}
