// ?rva000ADF90@Rva000ADF90@@QAEXPBUCoord3D@@ME@Z
// partial score=0.7369894870978018 date=2026-10-10
// cl: /O1 /G7 /arch:SSE /MD /EHsc /DNDEBUG
__declspec(dllimport) double __cdecl floor(double);__declspec(dllimport) double __cdecl ceil(double);
static __forceinline int FloorResultInt(float f){int out;__asm {
 fld f
 fistp out
}
 return out;}
struct Coord3D {float x,y,z;};struct Region2D {int left,top,right,bottom;};
class Rva000ADF90MaskView {public:__declspec(noinline) void markBit(int,int,unsigned char);private:char pad[8];int width,height;char pad1[0x34-0x10];int pitch;char pad2[0x50-0x38];unsigned char*begin,*end;};
void Rva000ADF90MaskView::markBit(int x,int y,unsigned char value){if(x<0)return;if(y<0)return;if(y>=height)return;if(x>=width)return;int i=pitch*y+(x>>3);if((unsigned)i>=(unsigned)(end-begin))return;unsigned char*slot=begin+i;if(value)*slot|=(unsigned char)(1<<(x&7));else *slot&=(unsigned char)~(1<<(x&7));}
class TerrainView {public:
virtual void slot0();
virtual void slot1();
virtual void slot2();
virtual void slot3();
virtual void slot4();
virtual void slot5();
virtual void slot6();
virtual void slot7();
virtual void slot8();
virtual void slot9();
virtual void slot10();
virtual void slot11();
virtual void slot12();
virtual void slot13();
virtual void slot14();
virtual void slot15();
virtual void slot16();
virtual void slot17();
virtual void slot18();
virtual void slot19();
virtual void slot20();
virtual void slot21();
virtual void slot22();
virtual void slot23();
virtual void slot24();
virtual void slot25();
virtual void slot26();
virtual void slot27();
virtual void slot28();
virtual void slot29();
virtual void slot30();
virtual void slot31();
virtual void slot32();
virtual void slot33();
virtual void slot34();
virtual void slot35();
virtual void slot36();
virtual void slot37();
virtual void slot38();
virtual void slot39();
virtual void slot40();
virtual void slot41();
virtual void slot42();
virtual void slot43();
virtual void slot44();
virtual void slot45();
virtual void slot46();
virtual void slot47();
virtual void slot48();
virtual void slot49();
virtual void slot50();
virtual void slot51();
virtual void slot52();
virtual void slot53();
virtual void slot54();
virtual void slot55();
virtual void slot56();
virtual void slot57();
virtual void slot58();
virtual void slot59();
virtual void slot60();
virtual void slot61();
virtual void slot62();
virtual void slot63();
virtual void slot64();
virtual void slot65();
virtual void slot66();
virtual void slot67();
virtual void slot68();
virtual void slot69();
virtual void slot70();
virtual void slot71();
virtual void slot72();
virtual void slot73();
virtual void slot74();
virtual void slot75();
virtual void slot76();
virtual void slot77();
virtual void slot78();
virtual void slot79();
virtual void slot80();
virtual void slot81();
virtual void slot82();
virtual void slot83();
virtual void slot84();
virtual void slot85();
virtual void slot86();
virtual void slot87();
virtual void slot88();
virtual void slot89();
virtual void slot90();
virtual void slot91();
virtual void slot92();
virtual void slot93();
virtual void slot94();
virtual void slot95();
virtual void slot96();
virtual void slot97();
virtual void slot98();
virtual void slot99();
virtual void slot100();
virtual void slot101();
virtual void slot102();
virtual void slot103();
virtual void slot104();
virtual void slot105();
virtual void slot106();
virtual void slot107();
virtual void slot108();
virtual void slot109();
virtual void slot110();
virtual void slot111();
virtual void slot112();
virtual void slot113();
virtual void slot114();
virtual void slot115();
virtual void slot116();
virtual void slot117();
virtual void slot118();
virtual void slot119();
virtual void slot120();
virtual void slot121();
virtual void slot122();
virtual void slot123();
virtual void slot124();
virtual void slot125();
virtual void slot126();
virtual void slot127();
virtual void slot128();
virtual void slot129();
virtual void slot130();
virtual void slot131();
virtual void slot132();
virtual void slot133();
virtual void slot134();
virtual void slot135();
virtual void UpdateMask(const Region2D*,Rva000ADF90MaskView*,bool);};
class BaseHeightMapRenderObjClass;extern BaseHeightMapRenderObjClass*TheTerrainRenderObject;
class Rva000ADF90 {public:void rva000ADF90(const Coord3D*,float,unsigned char);private:char pad[8];int width,height,border;};
void Rva000ADF90::rva000ADF90(const Coord3D*p,float radius,unsigned char value){
 int minX=FloorResultInt((float)floor((p->x-radius)*0.1f))+border;
 int minY=FloorResultInt((float)floor((p->y-radius)*0.1f))+border;
 if(minX<0)minX=0;if(minY<0)minY=0;
 int maxX=FloorResultInt((float)ceil((radius+p->x)*0.1f))+border;
 int maxY=FloorResultInt((float)ceil((radius+p->y)*0.1f))+border;
 if(maxX>width)maxX=width;if(maxY>height)maxY=height;
 float radiusSquared=radius*radius;Coord3D center=*p;center.x+=border*10.0f;center.y+=border*10.0f;
 for(int x=minX;x<maxX;++x){for(int y=minY;y<maxY;++y){float dx=(x+0.5f)*10.0f-center.x;float dy=(y+0.5f)*10.0f-center.y;float dist=dx*dx+dy*dy;if(dist<radiusSquared)((Rva000ADF90MaskView*)this)->markBit(x,y,value);}}
 Region2D box={minX,minY,maxX,maxY};if(TheTerrainRenderObject)((TerrainView*)TheTerrainRenderObject)->UpdateMask(&box,(Rva000ADF90MaskView*)this,false);
}
