// ?draw@W3DRadar@@QAEXHHHHH@Z
// partial score=1.0 date=2026-10-09
// cl: /O1 /G7 /arch:SSE /DNDEBUG /MD /EHsc /Ireference/shims/moduledata
// Native5053E..50A60 RET20. BF1 f989 W3DRadar::draw / ZH guide; target
// independently supplies five-arg alpha, dirty-overlay and display clipping.
#include "Common/Snapshot.h"
struct ICoord2D{int x,y;};
struct Coord3D{float x,y,z;};
struct Region3D{Coord3D lo,hi;float width()const{return hi.x-lo.x;}float height()const{return hi.y-lo.y;}};
class Image;class RadarObject;
class Player{public:bool hasRadar()const;};
class PlayerList{public:char pad[0x10];Player*local;};extern PlayerList*ThePlayerList;
class W3DRadarResetSurface{public:void*ptr;W3DRadarResetSurface(){}W3DRadarResetSurface(const W3DRadarResetSurface&);~W3DRadarResetSurface();void clear(unsigned int);};
class CursorTextureSlot{public:void*ptr;W3DRadarResetSurface Get_Surface_Level();};
class Display{public:
virtual void slot0();
virtual void slot1();
virtual void slot2();
virtual void slot3();
virtual void slot4();
virtual void slot5();
virtual void slot6();
virtual void slot7();
virtual void slot8();
virtual void slot9();
virtual void slot10();
virtual void slot11();
virtual void slot12();
virtual void slot13();
virtual void slot14();
virtual void slot15();
virtual void slot16();
virtual void slot17();
virtual void slot18();
virtual void slot19();
virtual void slot20();
virtual void slot21();
virtual void slot22();
virtual void slot23();
virtual void slot24();
virtual void slot25();
virtual void slot26();
virtual void slot27();
virtual void slot28();
virtual void slot29();
virtual void slot30();
virtual void slot31();
virtual void slot32();
virtual void slot33();
virtual void slot34();
virtual void slot35();
virtual void slot36();
virtual void slot37();
virtual void slot38();
virtual void slot39();
virtual void slot40();
virtual void slot41();
virtual void setClip(void*);
virtual void slot43();
virtual void resetClip(void*);
};extern Display*TheDisplay;
class W3DDisplay{public:void rva0004D664(float,float,float,float,float,int);void rva0004D6B3(Image*,float,float,float,float,int,int);};
class Rva0004263F{public:void rva0004263F(float,float,float,float,int);};
class View{public:
virtual void slot0();
virtual void slot1();
virtual void slot2();
virtual void slot3();
virtual void slot4();
virtual void slot5();
virtual void slot6();
virtual void slot7();
virtual void slot8();
virtual void slot9();
virtual void slot10();
virtual void slot11();
virtual void slot12();
virtual void slot13();
virtual void slot14();
virtual void slot15();
virtual void slot16();
virtual void slot17();
virtual void slot18();
virtual void slot19();
virtual void slot20();
virtual void slot21();
virtual void slot22();
virtual void slot23();
virtual void slot24();
virtual void slot25();
virtual void slot26();
virtual void slot27();
virtual void slot28();
virtual void slot29();
virtual void slot30();
virtual void slot31();
virtual void slot32();
virtual void slot33();
virtual void slot34();
virtual void slot35();
virtual void slot36();
virtual void slot37();
virtual void slot38();
virtual void slot39();
virtual void slot40();
virtual void slot41();
virtual void slot42();
virtual void slot43();
virtual void slot44();
virtual void slot45();
virtual void slot46();
virtual void slot47();
virtual void slot48();
virtual void slot49();
virtual void slot50();
virtual void slot51();
virtual void slot52();
virtual void slot53();
virtual void slot54();
virtual void slot55();
virtual void slot56();
virtual void slot57();
virtual void slot58();
virtual void slot59();
virtual void slot60();
virtual void slot61();
virtual void slot62();
virtual void slot63();
virtual float getAngle();
virtual void slot65();
virtual void slot66();
virtual void slot67();
virtual void slot68();
virtual void slot69();
virtual void slot70();
virtual void slot71();
virtual void slot72();
virtual float getZoom();
};extern View*TheTacticalView;
class GameClient{public:
virtual void slot0();
virtual void slot1();
virtual void slot2();
virtual void slot3();
virtual void slot4();
virtual void slot5();
virtual void slot6();
virtual void slot7();
virtual void slot8();
virtual void slot9();
virtual void slot10();
virtual void slot11();
virtual void slot12();
virtual void slot13();
virtual void slot14();
virtual void slot15();
virtual void slot16();
virtual void slot17();
virtual void slot18();
virtual void slot19();
virtual void slot20();
virtual void slot21();
virtual void slot22();
virtual void slot23();
virtual void slot24();
virtual void slot25();
virtual void slot26();
virtual void slot27();
virtual void slot28();
virtual void slot29();
virtual void slot30();
virtual unsigned getFrame();
};extern GameClient*TheGameClient;
class SubsystemInterface{public:virtual~SubsystemInterface();virtual void draw(int,int,int,int)=0;};
class Radar:public Snapshot,public SubsystemInterface{public:void findDrawPositions(int,int,int,int,ICoord2D*,ICoord2D*);void rva0004F515(int,int,int,int);};extern Radar*TheRadar;
class W3DRadar:public Radar{public:void draw(int,int,int,int,int);
void rva00050125(const RadarObject*,const CursorTextureSlot*,int);
void rva0004E5A2(int,int,int,int,int);
void reconstructViewBox();void drawViewBox(int,int,int,int,int);
char pad08[0x14-8];RadarObject*list1;RadarObject*list2;
char pad1c[0x1434-0x1c];Region3D extent;
float clipRect[4];bool clip;char pad145d[0x1464-0x145d];bool dirty;char pad1465[3];
int terrainFormat;Image*terrain;CursorTextureSlot terrainTex,altTerrainTex;
int overlayFormat;Image*shroud;CursorTextureSlot overlayTex;
int ringFormat;Image*ring;CursorTextureSlot ringTex;
int iconFormat;Image*overlay;CursorTextureSlot shroudTex;
char pad149c[0x14d4-0x149c];bool rebuild;bool flag1,flag2;char pad14d7;float angle,zoom;
};
int Rva0004D76EBlend(int,int);
void W3DRadar::draw(int pixelX,int pixelY,int width,int height,int color){
Player*player=ThePlayerList->local;
if(!player->hasRadar()&&!*(bool*)((char*)TheRadar+0x11))return;
if(clip)TheDisplay->setClip(clipRect);
ICoord2D ul,lr;findDrawPositions(pixelX,pixelY,width,height,&ul,&lr);
int scaledWidth=lr.x-ul.x,scaledHeight=lr.y-ul.y;
if(!flag1&&!flag2){int fillColor=Rva0004D76EBlend(0xff000000,color);int lineColor=Rva0004D76EBlend(0xff323232,color);
if(extent.width()/width>=extent.height()/height){
((Rva0004263F*)TheDisplay)->rva0004263F(pixelX,pixelY,width,ul.y-pixelY-1,fillColor);
((Rva0004263F*)TheDisplay)->rva0004263F(pixelX,lr.y+1,width,pixelY+height-lr.y-1,fillColor);
((W3DDisplay*)TheDisplay)->rva0004D664(pixelX,ul.y,pixelX+width,ul.y,1,lineColor);
((W3DDisplay*)TheDisplay)->rva0004D664(pixelX,lr.y+1,pixelX+width,lr.y+1,1,lineColor);
}else{
((Rva0004263F*)TheDisplay)->rva0004263F(pixelX,pixelY,ul.x-pixelX-1,height,fillColor);
((Rva0004263F*)TheDisplay)->rva0004263F(lr.x+1,pixelY,width-(lr.x-pixelX)-1,height,fillColor);
((W3DDisplay*)TheDisplay)->rva0004D664(ul.x,pixelY,ul.x,pixelY+height,1,lineColor);
((W3DDisplay*)TheDisplay)->rva0004D664(lr.x+1,pixelY,lr.x+1,pixelY+height,1,lineColor);
}}
((W3DDisplay*)TheDisplay)->rva0004D6B3(terrain,ul.x,ul.y,lr.x,lr.y,color,2);
if(dirty||TheGameClient->getFrame()%6==0){
overlayTex.Get_Surface_Level().clear(0);
rva00050125(list1,&overlayTex,color);rva00050125(list2,&overlayTex,color);
}
((W3DDisplay*)TheDisplay)->rva0004D6B3(overlay,ul.x,ul.y,lr.x,lr.y,color,2);
((W3DDisplay*)TheDisplay)->rva0004D6B3(shroud,ul.x,ul.y,lr.x,lr.y,color,2);
((W3DDisplay*)TheDisplay)->rva0004D6B3(ring,pixelX,pixelY,pixelX+width,pixelY+height,color,2);
rva0004E5A2(ul.x,ul.y,scaledWidth,scaledHeight,color);
rva0004F515(ul.x,ul.y,scaledWidth,scaledHeight);
if(TheTacticalView->getZoom()!=zoom)rebuild=true;
if(TheTacticalView->getAngle()!=angle)rebuild=true;
if(rebuild==true)reconstructViewBox();
drawViewBox(ul.x,ul.y,scaledWidth,scaledHeight,color);
if(clip)TheDisplay->resetClip(0);
dirty=false;
}
