// cl: /O1 /DNDEBUG /MD /EHsc
// TU Code/GameEngine/Source/GameLogic/Object/Die/CrushDie.cpp: generated by tools/tu_skeleton.py from tu_map.csv (approved rows, retail order)

class Thing;

class ModuleData;

// upstream layout: reference/CnC_Generals_Zero_Hour/GeneralsMD/Code/GameEngine/Include/Common/Module.h
class ObjectModule
{
public:
	virtual void objectModuleAnchor();
	ObjectModule( Thing *thing, const ModuleData *moduleData );

private:
	unsigned char m_data[8];
};

// upstream layout: reference/CnC_Generals_Zero_Hour/GeneralsMD/Code/GameEngine/Include/GameLogic/Module/BehaviorModule.h
// Real 34-pure interface (all =0, vtable all __purecall) to match kept copy from AIUpdate.cpp;
// single-anchor placeholder emitted 1-entry vtable vs real 34-entry, causing LINK-COMDAT.
class BodyModuleInterface;

class CollideModuleInterface;

class ContainModuleInterface;

class CreateModuleInterface;

class DamageModuleInterface;

class DestroyModuleInterface;

class DieModuleInterface;

class SpecialPowerModuleInterface;

class UpdateModuleInterface;

class UpgradeModuleInterface;

class ParkingPlaceBehaviorInterface;

class RebuildHoleBehaviorInterface;

class BridgeBehaviorInterface;

class BridgeTowerBehaviorInterface;

class BridgeScaffoldBehaviorInterface;

class OverchargeBehaviorInterface;

class TransportPassengerInterface;

class CaveInterface;

class LandMineInterface;

class ProjectileUpdateInterface;

class AIUpdateInterface;

class ExitInterface;

class DockUpdateInterface;

class RailedTransportDockUpdateInterface;

class SlowDeathBehaviorInterface;

class SpecialPowerUpdateInterface;

class SlavedUpdateInterface;

class ProductionUpdateInterface;

class HordeUpdateInterface;

class PowerPlantUpdateInterface;

class SpawnBehaviorInterface;

class CountermeasuresBehaviorInterface;

class BehaviorModuleInterface
{
public:
	virtual BodyModuleInterface *getBody() = 0;
	virtual CollideModuleInterface *getCollide() = 0;
	virtual ContainModuleInterface *getContain() = 0;
	virtual CreateModuleInterface *getCreate() = 0;
	virtual DamageModuleInterface *getDamage() = 0;
	virtual DestroyModuleInterface *getDestroy() = 0;
	virtual DieModuleInterface *getDie() = 0;
	virtual SpecialPowerModuleInterface *getSpecialPower() = 0;
	virtual UpdateModuleInterface *getUpdate() = 0;
	virtual UpgradeModuleInterface *getUpgrade() = 0;
	virtual ParkingPlaceBehaviorInterface *getParkingPlaceBehaviorInterface() = 0;
	virtual RebuildHoleBehaviorInterface *getRebuildHoleBehaviorInterface() = 0;
	virtual BridgeBehaviorInterface *getBridgeBehaviorInterface() = 0;
	virtual BridgeTowerBehaviorInterface *getBridgeTowerBehaviorInterface() = 0;
	virtual BridgeScaffoldBehaviorInterface *getBridgeScaffoldBehaviorInterface() = 0;
	virtual OverchargeBehaviorInterface *getOverchargeBehaviorInterface() = 0;
	virtual TransportPassengerInterface *getTransportPassengerInterface() = 0;
	virtual CaveInterface *getCaveInterface() = 0;
	virtual LandMineInterface *getLandMineInterface() = 0;
	virtual DieModuleInterface *getEjectPilotDieInterface() = 0;
	virtual ProjectileUpdateInterface *getProjectileUpdateInterface() = 0;
	virtual AIUpdateInterface *getAIUpdateInterface() = 0;
	virtual ExitInterface *getUpdateExitInterface() = 0;
	virtual DockUpdateInterface *getDockUpdateInterface() = 0;
	virtual RailedTransportDockUpdateInterface *getRailedTransportDockUpdateInterface() = 0;
	virtual SlowDeathBehaviorInterface *getSlowDeathBehaviorInterface() = 0;
	virtual SpecialPowerUpdateInterface *getSpecialPowerUpdateInterface() = 0;
	virtual SlavedUpdateInterface *getSlavedUpdateInterface() = 0;
	virtual ProductionUpdateInterface *getProductionUpdateInterface() = 0;
	virtual HordeUpdateInterface *getHordeUpdateInterface() = 0;
	virtual PowerPlantUpdateInterface *getPowerPlantUpdateInterface() = 0;
	virtual SpawnBehaviorInterface *getSpawnBehaviorInterface() = 0;
	virtual CountermeasuresBehaviorInterface *getCountermeasuresBehaviorInterface() = 0;
	virtual const CountermeasuresBehaviorInterface *getCountermeasuresBehaviorInterface() const = 0;
};

// upstream layout: reference/CnC_Generals_Zero_Hour/GeneralsMD/Code/GameEngine/Include/GameLogic/Module/DieModule.h
class DieModuleInterface
{
public:
	virtual void dieModuleInterfaceAnchor() = 0;
};

// upstream layout: reference/CnC_Generals_Zero_Hour/GeneralsMD/Code/GameEngine/Include/GameLogic/Module/DieModule.h
class DieModule : public ObjectModule,
	public BehaviorModuleInterface,
	public DieModuleInterface
{
public:
	DieModule( Thing *thing, const ModuleData *moduleData )
		: ObjectModule( thing, moduleData )
	{
	}
};

// ?rva000486155@CrushDie@@SA?AW4NameKeyType@@XZ @0x486155
// (69B): cached pool-name key for CrushDie. The class
// identity comes from the pool-name string the body pushes
// ("CrushDie"); the body guards a function-local static
// key fetched once through TheNameKeyGenerator. It is NOT getClassMemoryPool:
// retail stores nameToKey's return (a key, not a pool pointer) and returns it,
// and the address carries no getClassMemoryPool row anywhere. /EHsc for the
// static-guard EH prologue; globals are TU-local externs (DIR32 slots patch
// from retail, no pins; nameToKey resolves via its matched row).

enum NameKeyType
{
	NK_UNKNOWN = 0
};

class NameKeyGenerator
{
public:
	NameKeyType nameToKey(const char *name);
};

extern NameKeyGenerator *TheNameKeyGenerator;

class CrushDie : public DieModule
{
public:
	CrushDie( Thing *thing, const ModuleData *moduleData );
public:
	static NameKeyType rva000486155();
};

// ---- from Code/GameEngine/Source/GameLogic/Object/Die/CrushDiePoolKey.cpp

// ?rva000486155@CrushDie@@SA?AW4NameKeyType@@XZ
NameKeyType CrushDie::rva000486155()
{
	static NameKeyType TheCrushDiePoolKey =
		TheNameKeyGenerator->nameToKey("CrushDie");
	return TheCrushDiePoolKey;
}

// tu-skeleton: 0x0048619A 327B (unledgered) -- unmatched, no code, never credited

// ---- from Code/GameEngine/Source/GameLogic/Object/Die/CrushDie.cpp

CrushDie::CrushDie( Thing *thing, const ModuleData *moduleData )
	: DieModule( thing, moduleData )
{
}
