// cl: /DNDEBUG /MD /EHsc
// TU Code/GameEngine/Source/GameLogic/Object/Die/DestroyDie.cpp: generated by tools/tu_skeleton.py from tu_map.csv (approved rows, retail order)

class Thing;

class ModuleData;

class DamageInfo;

class Object;

typedef bool Bool;

class GameLogic
{
public:
	void destroyObject(Object *obj);
};

extern GameLogic *TheGameLogic;

// upstream layout: reference/CnC_Generals_Zero_Hour/GeneralsMD/Code/GameEngine/Include/Common/Module.h
class ObjectModule
{
public:
	virtual void objectModuleAnchor();
	ObjectModule( Thing *thing, const ModuleData *moduleData );
	Object *getObject() const { return m_object; }

private:
	unsigned char m_data[4];
	Object *m_object; // +0x08
};

// upstream layout: reference/CnC_Generals_Zero_Hour/GeneralsMD/Code/GameEngine/Include/GameLogic/Module/BehaviorModule.h
class BehaviorModuleInterface
{
public:
	virtual void behaviorModuleInterfaceAnchor();
};

// upstream layout: reference/CnC_Generals_Zero_Hour/GeneralsMD/Code/GameEngine/Include/GameLogic/Module/DieModule.h
class DieModuleInterface
{
public:
	virtual void onDie( const DamageInfo *damageInfo ) = 0;
};

// upstream layout: reference/CnC_Generals_Zero_Hour/GeneralsMD/Code/GameEngine/Include/GameLogic/Module/DieModule.h
class DieModule : public ObjectModule,
	public BehaviorModuleInterface,
	public DieModuleInterface
{
public:
	DieModule( Thing *thing, const ModuleData *moduleData )
		: ObjectModule( thing, moduleData )
	{
	}
protected:
	Bool isDieApplicable( const DamageInfo *damageInfo ) const;
};

// ?rva0004864C9@DestroyDie@@SA?AW4NameKeyType@@XZ @0x4864C9
// (69B): cached pool-name key for DestroyDie. The class
// identity comes from the pool-name string the body pushes
// ("DestroyDie"); the body guards a function-local static
// key fetched once through TheNameKeyGenerator. It is NOT getClassMemoryPool:
// retail stores nameToKey's return (a key, not a pool pointer) and returns it,
// and the address carries no getClassMemoryPool row anywhere. /EHsc for the
// static-guard EH prologue; globals are TU-local externs (DIR32 slots patch
// from retail, no pins; nameToKey resolves via its matched row).

enum NameKeyType
{
	NK_UNKNOWN = 0
};

class NameKeyGenerator
{
public:
	NameKeyType nameToKey(const char *name);
};

extern NameKeyGenerator *TheNameKeyGenerator;

class DestroyDie : public DieModule
{
public:
	DestroyDie( Thing *thing, const ModuleData *moduleData );
public:
	virtual void onDie( const DamageInfo *damageInfo );
public:
	static NameKeyType rva0004864C9();
};

// ---- from Code/GameEngine/Source/GameLogic/Object/Die/DestroyDiePoolKey.cpp

// ?rva0004864C9@DestroyDie@@SA?AW4NameKeyType@@XZ
NameKeyType DestroyDie::rva0004864C9()
{
	static NameKeyType TheDestroyDiePoolKey =
		TheNameKeyGenerator->nameToKey("DestroyDie");
	return TheDestroyDiePoolKey;
}

// ---- from Code/GameEngine/Source/GameLogic/Object/Die/DestroyDie.cpp

DestroyDie::DestroyDie( Thing *thing, const ModuleData *moduleData )
	: DieModule( thing, moduleData )
{
}

// ?onDie@DestroyDie@@UAEXPBVDamageInfo@@@Z retail 0x00486554 35B: Zero Hour's
// DestroyDie::onDie, entered through the DieModuleInterface vtable at VA
// 0x00C4ACC4 with this on the +0x10 interface (hence the -0x10 adjust); a
// start missing from the Ghidra inventory.
void DestroyDie::onDie( const DamageInfo *damageInfo )
{
	if (!isDieApplicable(damageInfo))
		return;
	TheGameLogic->destroyObject(getObject());
}

// tu-skeleton: 0x00486538 28B ??_GRva004864AA@@UAEPAXI@Z -- matched in Code/GameEngine/Source/GameLogic/Object/Die/DieModuleDerived.cpp (not merged yet)
