// cl: /DNDEBUG /MD /GX
// TU Code/GameEngine/Source/GameLogic/Object/Die/KeepObjectDie.cpp: generated by tools/tu_skeleton.py from tu_map.csv (approved rows, retail order)

// ?rva000486C95@KeepObjectDie@@SA?AW4NameKeyType@@XZ @0x486c95
// (69B): cached pool-name key for KeepObjectDie. The class
// identity comes from the pool-name string the body pushes
// ("KeepObjectDie"); the body guards a function-local static
// key fetched once through TheNameKeyGenerator. It is NOT getClassMemoryPool:
// retail stores nameToKey's return (a key, not a pool pointer) and returns it,
// and the address carries no getClassMemoryPool row anywhere. /EHsc for the
// static-guard EH prologue; globals are TU-local externs (DIR32 slots patch
// from retail, no pins; nameToKey resolves via its matched row).

enum NameKeyType
{
	NK_UNKNOWN = 0
};

class NameKeyGenerator
{
public:
	NameKeyType nameToKey(const char *name);
};

extern NameKeyGenerator *TheNameKeyGenerator;

class KeepObjectDie
{
public:
	static NameKeyType rva000486C95();
};

// ?rva00486CF6@Rva00486B56@@QAEXPBVDamageInfo@@@Z @ 0x00486CF6 (125B). Die slot 12 onDie-style via Object/GameLogic/Radar.
// Evidence: vtable slot 12 of 0x0084AEBC class Rva00486B56; retail uses [esi-8] Object [esi-0x0C] +0x38/+0x3C [esi-0x10] DieModule calling rowed getControllingPlayer destroyObject setSpecial isDieApplicable Radar::addObject; no callers.
class Player;

class Object;

class GameLogic;

class Radar;

class DamageInfo;

enum ModelConditionFlagType
{
	MCF_335 = 0x14F
};

class Rva002AA22AByteField
{
public:
	unsigned char get() const;
};

class Player : public Rva002AA22AByteField
{
};

class Object
{
public:
	Player *getControllingPlayer() const;
	void setSpecialModelConditionState(ModelConditionFlagType a, unsigned int b);
};

class GameLogic
{
public:
	void destroyObject(Object *obj);
};

extern GameLogic *TheGameLogic;

class Radar
{
public:
	void addObject(Object *obj);
};

extern Radar *TheRadar;

struct Rva00486CF6_P04
{
	char m_pad[0x38];
	unsigned int m_38;
	unsigned char m_3C;
};

class DieModule
{
	friend class Rva00486B56;
protected:
	bool isDieApplicable(const DamageInfo *damageInfo) const;
public:
	Rva00486CF6_P04 *m_04;
	Object *m_08;
};

class Rva00486B56
{
public:
	void rva00486CF6(const DamageInfo *damageInfo);
};

// ---- from Code/GameEngine/Source/GameLogic/Object/Die/KeepObjectDiePoolKey.cpp

// ?rva000486C95@KeepObjectDie@@SA?AW4NameKeyType@@XZ
NameKeyType KeepObjectDie::rva000486C95()
{
	static NameKeyType TheKeepObjectDiePoolKey =
		TheNameKeyGenerator->nameToKey("KeepObjectDie");
	return TheKeepObjectDiePoolKey;
}

// tu-skeleton: 0x00486CDA 28B ??_GRva00486C76@@UAEPAXI@Z -- matched in Code/GameEngine/Source/GameLogic/Object/Die/DieModuleDerived.cpp (not merged yet)

// ---- from Code/GameEngine/Source/GameLogic/Object/Die/Rva00486CF6OnDie.cpp

void Rva00486B56::rva00486CF6(const DamageInfo *damageInfo)
{
	Object *obj = *(Object **)((char *)this - 8);
	Player *player = (obj != 0) ? obj->getControllingPlayer() : 0;
	if (player != 0 && player->get() != 0)
	{
		TheGameLogic->destroyObject(obj);
		return;
	}
	(*(Object **)((char *)this - 8))->setSpecialModelConditionState(MCF_335, (*(Rva00486CF6_P04 **)((char *)this - 0x0C))->m_38);
	if (!((DieModule *)((char *)this - 0x10))->isDieApplicable(damageInfo))
		return;
	if ((*(Rva00486CF6_P04 **)((char *)this - 0x0C))->m_3C == 0)
		return;
	if (obj == 0)
		return;
	if (*(int *)((char *)obj + 0x260) != 0)
		return;
	TheRadar->addObject(obj);
}

// tu-skeleton: 0x00486D73 165B ??0KeepObjectDie@@QAE@PAVThing@@PBVModuleData@@@Z -- matched in Code/GameEngine/Source/GameLogic/Object/Die/KeepObjectDieCtor.cpp (not merged yet)
