// cl: /Ireference/shims/bfme2_ascii /ICode/GameEngine/Include /O1 /arch:SSE /MD /DNDEBUG /DWIN32 /D_WINDOWS
// TU Code/GameEngine/Source/GameLogic/Object/Die/RebuildHoleExposeDie.cpp: generated by tools/tu_skeleton.py from tu_map.csv (approved rows, retail order)
#pragma comment(linker, "/alternatename:_vtbl_00C4A650=??_7CreateCrateDie@@6BBehaviorModuleInterface@@@")

//
// ??0RebuildHoleExposeDieModuleData@@QAE@XZ,
// retail 0x0048671F, 38 bytes. Frameless ctor over the pinned SEH base
// (??0DestroyDieModuleData@@QAE@XZ at 0x253510 shared with the UpgradeDie family):
// base call then the distinctive vtable literal 0x00C4AD40 then the
// and-zero of the HoleName word at +0x38 then the float zeros of
// HoleMaxHealth at +0x3C and FadeInTimeSeconds at +0x40 (/arch:SSE keeps
// them as xorps plus movss) and the true byte at +0x44. Size 0x48 matches
// the 0x24CB18 factory news. Class identity is the rowed
// RebuildHoleExposeDieModuleData::buildFieldParse proc (HoleName plus
// HoleMaxHealth table 0x00C4AE00) beside the rowed RebuildHoleExposeDie
// pool key (0x486792) closing this cluster. The holeName pointer anchors
// the and-zero below the vtable store (else it hoists above it).

#include "Common/BfmeModuleData.h"

class DestroyDieModuleData : public ModuleData
{
public:
	DestroyDieModuleData();
	virtual ~DestroyDieModuleData();

private:
	unsigned char m_pad[0x34]; // +4..0x37 (BFME2 base runs 4 wider than BFME1's 0x34)
};

// Vtable 0x00C4AD40: slot 0 the rowed deleting dtor 0x004869B0 over the rowed
// dtor 0x004869CC, slots 1-30 the shared ModuleData bodies.
class RebuildHoleExposeDieModuleData : public DestroyDieModuleData
{
public:
	RebuildHoleExposeDieModuleData();
	virtual ~RebuildHoleExposeDieModuleData();

private:
	int m_holeName; // +0x38 (name key data word)
	float m_holeMaxHealth; // +0x3C
	float m_fadeInTimeSeconds; // +0x40
	bool m_transferAttackers; // +0x44
};

// Identity: ModuleFactory registers this module as "RebuildHoleExposeDie" (addModule pairs
// the name with its factories); formerly misnamed RebuildHoleExposeDieUpdate.
//
// ??0RebuildHoleExposeDie@@QAE@PAVThing@@PBVModuleData@@@Z, retail
// 0x00486768 (42 bytes). Dedicated TU: the behavior ctor runs the pinned
// Die-family intermediate base ctor (thing plus data, this in ecx per the
// single-inheritance vptr-at-zero layout), then installs the behavior
// vtable 0x00C4AE54 and re-stores the inherited +0x0C/+0x10 secondary slots
// with literals (Oathbreakers behavior precedent). The TU-local base
// carries a declared-only virtual dtor: vptr at +0 keeps the base call
// this-direct (no lea) and the derived declared-only virtual dtor emits
// the vtable store in position, both with zero EH code so the body stays
// frameless with callee-cleaned args. Class identity is the tight
// RebuildHole cluster: the rowed ModuleData proc 0x48675D ends exactly
// where this ctor begins, the 56B Update instance factory 0x24CAE0
// sole-calls it right before the rowed ModuleData factory, and the rowed
// ModuleData ctor plus factory plus pool key close the file-unit. True
// size 42 corrects the 39B park note which cut the ret.

extern "C" const void *const vtbl_00C4A650[];

class Thing;

class ModuleData;

// Opaque Die-family behavior intermediate base; ctor resolves to its pin.
// Single inheritance with a declared-only virtual dtor puts the vptr (and
// the base) at +0, so the base call takes this directly. Slots mirror the
// retail stores.
class Rva0045CEBDUpdate
{
public:
	Rva0045CEBDUpdate(Thing *thing, const ModuleData *moduleData);
	virtual ~Rva0045CEBDUpdate();

protected:
	void *m_owner;
	int m_pad08;
	const void *m_secondary0C;
	const void *m_secondary10;
};

// ?rva000486792@RebuildHoleExposeDie@@SA?AW4NameKeyType@@XZ @0x486792
// (69B): cached pool-name key for RebuildHoleExposeDie. The class
// identity comes from the pool-name string the body pushes
// ("RebuildHoleExposeDie"); the body guards a function-local static
// key fetched once through TheNameKeyGenerator. It is NOT getClassMemoryPool:
// retail stores nameToKey's return (a key, not a pool pointer) and returns it,
// and the address carries no getClassMemoryPool row anywhere. /EHsc for the
// static-guard EH prologue; globals are TU-local externs (DIR32 slots patch
// from retail, no pins; nameToKey resolves via its matched row).

enum NameKeyType
{
	NK_UNKNOWN = 0
};

class NameKeyGenerator
{
public:
	NameKeyType nameToKey(const char *name);
};

extern NameKeyGenerator *TheNameKeyGenerator;

class RebuildHoleExposeDie : public Rva0045CEBDUpdate
{
public:
	RebuildHoleExposeDie(Thing *thing, const ModuleData *moduleData);
public:
	virtual ~RebuildHoleExposeDie();
public:
	static NameKeyType rva000486792();
};

// tu-skeleton: 0x004866F3 44B ?xfer@RebuildHoleExposeDie@@MAEXPAVXfer@@@Z -- matched in Code/GameEngine/Source/GameLogic/Object/Die/RebuildHoleExposeDieXfer.cpp (not merged yet)

// ---- from Code/GameEngine/Source/GameLogic/Object/Die/RebuildHoleExposeDieModuleDataCtor.cpp

// ??0RebuildHoleExposeDieModuleData@@QAE@XZ @0x48671F
RebuildHoleExposeDieModuleData::RebuildHoleExposeDieModuleData()
{
	int *holeName = &m_holeName;
	*holeName &= 0;
	m_holeMaxHealth = 0.0f;
	m_fadeInTimeSeconds = 0.0f;
	m_transferAttackers = true;
}

// tu-skeleton: 0x00486746 34B ?buildFieldParse@RebuildHoleExposeDieModuleData@@SAXAAVMultiIniFieldParse@@@Z -- matched in Code/GameEngine/Source/GameLogic/Object/Update/ModuleDataBuildFieldParseChained.cpp (not merged yet)

// ---- from Code/GameEngine/Source/GameLogic/Object/Die/RebuildHoleExposeDieUpdateCtor.cpp

  // folded, 21 classes; via ??_7CreateCrateDie@@6BBehaviorModuleInterface@@@

// ??0RebuildHoleExposeDie@@QAE@PAVThing@@PBVModuleData@@@Z @0x486768
RebuildHoleExposeDie::RebuildHoleExposeDie(Thing *thing, const ModuleData *moduleData)
	: Rva0045CEBDUpdate(thing, moduleData)
{
	m_secondary0C = reinterpret_cast<const void *>(((unsigned int)vtbl_00C4A650));
	m_secondary10 = reinterpret_cast<const void *>(0x00C4AE50);
}

// ---- from Code/GameEngine/Source/GameLogic/Object/Die/RebuildHoleExposeDiePoolKey.cpp

// ?rva000486792@RebuildHoleExposeDie@@SA?AW4NameKeyType@@XZ
NameKeyType RebuildHoleExposeDie::rva000486792()
{
	static NameKeyType TheRebuildHoleExposeDiePoolKey =
		TheNameKeyGenerator->nameToKey("RebuildHoleExposeDie");
	return TheRebuildHoleExposeDiePoolKey;
}

// tu-skeleton: 0x004867D7 6B ?name@Rva004867D7Named@@QBEPBDXZ -- matched in Code/GameEngine/Source/Common/ModuleNameGetters.cpp (not merged yet)

// tu-skeleton: 0x004867DD 28B ??_GRebuildHoleExposeDie@@UAEPAXI@Z -- matched in Code/GameEngine/Source/GameLogic/Object/Die/DieModuleDeletingDtors.cpp (not merged yet)

// tu-skeleton: 0x004867F9 5B (unledgered) -- unmatched, no code, never credited

// tu-skeleton: 0x004867FE 434B (unledgered) -- unmatched, no code, never credited

// tu-skeleton: 0x004869CC 48B ??1RebuildHoleExposeDieModuleData@@UAE@XZ -- matched in Code/GameEngine/Source/GameLogic/Object/Die/RebuildHoleExposeDieModuleDataDtor.cpp (not merged yet)
