// cl: /DNDEBUG /DWIN32 /MD /EHsc /D_STLP_USE_STATIC_LIB
// stlport

// Evidence: retail 0x0028C7E3 (54 bytes) is byte-identical to the landed
// BitFlags getSingleBitFromName pair (0x000B42CA, 0x002AA2F9) except for the
// name-table DIR32: it reads 0x00DBC2C8, whose first entries are VETERAN,
// ELITE, HERO (104 names total). Same _strcmpi thunk at 0x00BBA518, same
// index-or-minus-one loop. ZH BitFlags.h declares the shared static shape.

#include <bitset>
#include <string.h>

typedef int Int;
typedef bool Bool;

// VeterancyNames104: the retail string table at VA 0xdbc2c8.
const char *VeterancyNames104[104] = {
	"VETERAN",
	"ELITE",
	"HERO",
	"PLAYER_UPGRADE",
	"PASSENGER_TYPE_ONE",
	"PASSENGER_TYPE_TWO",
	"GARRISONED",
	"CLOSE_RANGE",
	"RAMPAGE",
	"CONTESTING_BUILDING",
	"WEAPON_RIDER1",
	"WEAPON_RIDER2",
	"WEAPON_RIDER3",
	"WEAPON_RIDER4",
	"WEAPON_RIDER5",
	"WEAPON_RIDER6",
	"WEAPON_RIDER7",
	"WEAPON_RIDER8",
	"SPECIAL_ONE",
	"SPECIAL_TWO",
	"CONTAINED",
	"MOUNTED",
	"ENRAGED",
	"SPECIAL_UPGRADE",
	"WEAPONSET_TOGGLE_1",
	"WEAPONSET_TOGGLE_2",
	"WEAPONSET_TOGGLE_3",
	"WEAPONSET_HERO_MODE",
	"WEAPONSET_ONE_RING_MODE",
	"WEAPONSET_CREATE_A_HERO_WS_01",
	"WEAPONSET_CREATE_A_HERO_WS_02",
	"WEAPONSET_CREATE_A_HERO_WS_03",
	"WEAPONSET_CREATE_A_HERO_WS_04",
	"WEAPONSET_CREATE_A_HERO_WS_05",
	"WEAPONSET_CREATE_A_HERO_WS_06",
	"WEAPONSET_CREATE_A_HERO_WS_07",
	"WEAPONSET_CREATE_A_HERO_WS_08",
	"WEAPONSET_CREATE_A_HERO_WS_09",
	"WEAPONSET_CREATE_A_HERO_WS_10",
	"WEAPONSET_CREATE_A_HERO_WS_11",
	"WEAPONSET_CREATE_A_HERO_WS_12",
	"WEAPONSET_CREATE_A_HERO_WS_13",
	"WEAPONSET_CREATE_A_HERO_WS_14",
	"WEAPONSET_CREATE_A_HERO_WS_15",
	"WEAPONSET_CREATE_A_HERO_WS_16",
	"WEAPONSET_CREATE_A_HERO_WS_17",
	"WEAPONSET_CREATE_A_HERO_WS_18",
	"WEAPONSET_CREATE_A_HERO_WS_19",
	"WEAPONSET_CREATE_A_HERO_WS_20",
	"WEAPONSET_CREATE_A_HERO_WS_21",
	"WEAPONSET_CREATE_A_HERO_WS_22",
	"WEAPONSET_CREATE_A_HERO_WS_23",
	"WEAPONSET_CREATE_A_HERO_WS_24",
	"WEAPONSET_CREATE_A_HERO_WS_25",
	"WEAPONSET_CREATE_A_HERO_WS_26",
	"WEAPONSET_CREATE_A_HERO_WS_27",
	"WEAPONSET_CREATE_A_HERO_WS_28",
	"WEAPONSET_CREATE_A_HERO_WS_29",
	"WEAPONSET_CREATE_A_HERO_WS_30",
	"WEAPONSET_CREATE_A_HERO_WS_31",
	"WEAPONSET_CREATE_A_HERO_WS_32",
	"HIDDEN",
	"ARMORSET_CREATE_A_HERO_01",
	"ARMORSET_CREATE_A_HERO_02",
	"ARMORSET_CREATE_A_HERO_03",
	"ARMORSET_CREATE_A_HERO_04",
	"ARMORSET_CREATE_A_HERO_05",
	"ARMORSET_CREATE_A_HERO_06",
	"ARMORSET_CREATE_A_HERO_07",
	"ARMORSET_CREATE_A_HERO_08",
	"ARMORSET_CREATE_A_HERO_09",
	"ARMORSET_CREATE_A_HERO_10",
	"WEAPONSET_CREATE_A_HERO_WS_33",
	"WEAPONSET_CREATE_A_HERO_WS_34",
	"WEAPONSET_CREATE_A_HERO_WS_35",
	"WEAPONSET_CREATE_A_HERO_WS_36",
	"WEAPONSET_CREATE_A_HERO_WS_37",
	"WEAPONSET_CREATE_A_HERO_WS_38",
	"WEAPONSET_CREATE_A_HERO_WS_39",
	"WEAPONSET_CREATE_A_HERO_WS_40",
	"WEAPONSET_CREATE_A_HERO_WS_41",
	"WEAPONSET_CREATE_A_HERO_WS_42",
	"WEAPONSET_CREATE_A_HERO_WS_43",
	"WEAPONSET_CREATE_A_HERO_WS_44",
	"WEAPONSET_CREATE_A_HERO_WS_45",
	"WEAPONSET_CREATE_A_HERO_WS_46",
	"WEAPONSET_CREATE_A_HERO_WS_47",
	"WEAPONSET_CREATE_A_HERO_WS_48",
	"WEAPONSET_CREATE_A_HERO_WS_49",
	"WEAPONSET_CREATE_A_HERO_WS_50",
	"WEAPONSET_CREATE_A_HERO_WS_51",
	"WEAPONSET_CREATE_A_HERO_WS_52",
	"WEAPONSET_CREATE_A_HERO_WS_53",
	"WEAPONSET_CREATE_A_HERO_WS_54",
	"WEAPONSET_CREATE_A_HERO_WS_55",
	"WEAPONSET_CREATE_A_HERO_WS_56",
	"WEAPONSET_CREATE_A_HERO_WS_57",
	"WEAPONSET_CREATE_A_HERO_WS_58",
	"WEAPONSET_CREATE_A_HERO_WS_59",
	"WEAPONSET_CREATE_A_HERO_WS_60",
	"WEAPONSET_CREATE_A_HERO_WS_61",
	"WEAPONSET_CREATE_A_HERO_WS_62",
	"WEAPONSET_CREATE_A_HERO_WS_63",
	"WEAPONSET_CREATE_A_HERO_WS_64",
};

template <size_t NUMBITS>
class BitFlags
{
public:
	static Int getSingleBitFromName( const char *token );

private:
	_STL::bitset<NUMBITS> m_bits;
};

template <size_t NUMBITS>
Int BitFlags<NUMBITS>::getSingleBitFromName( const char *token )
{
	Int i = 0;
	for ( const char *const *name = VeterancyNames104; *name; ++name, ++i )
	{
		if ( _strcmpi( *name, token ) == 0 )
			return i;
	}
	return -1;
}

// ?getSingleBitFromName@?$BitFlags@$0GI@@@SAHPBD@Z
template Int BitFlags<104>::getSingleBitFromName( const char *token );
