// cl: /DNDEBUG /DWIN32 /MD /EHsc /D_STLP_USE_STATIC_LIB
// stlport

// Evidence: retail 0x0028C84F (54 bytes) is byte-identical to the landed
// BitFlags getSingleBitFromName pair except for the name-table DIR32: it
// reads 0x00DC0B40, whose first entries are SPECIAL_INVALID,
// SPECIAL_DAISY_CUTTER, SPECIAL_PARADROP_AMERICA (154 names total).
// Same _strcmpi thunk at 0x00BBA518.

#include <bitset>
#include <string.h>

typedef int Int;
typedef bool Bool;

// SpecialPowerNames: the retail string table at VA 0xdc0b40.
const char *SpecialPowerNames[154] = {
	"SPECIAL_INVALID",
	"SPECIAL_DAISY_CUTTER",
	"SPECIAL_PARADROP_AMERICA",
	"SPECIAL_CARPET_BOMB",
	"SPECIAL_CLUSTER_MINES",
	"SPECIAL_UP_FOR_GRABS_2",
	"SPECIAL_UP_FOR_GRABS_3",
	"SPECIAL_UP_FOR_GRABS_4",
	"SPECIAL_NEUTRON_MISSILE",
	"SPECIAL_UP_FOR_GRABS",
	"SPECIAL_DEFECTOR",
	"SPECIAL_TERROR_CELL",
	"SPECIAL_AMBUSH",
	"SPECIAL_BLACK_MARKET_NUKE",
	"SPECIAL_ANTHRAX_BOMB",
	"SPECIAL_SCUD_STORM",
	"SPECIAL_PRINCE_OF_DOL_ARMOTH",
	"SPECIAL_CRATE_DROP",
	"SPECIAL_A10_THUNDERBOLT_STRIKE",
	"SPECIAL_DETONATE_DIRTY_NUKE",
	"SPECIAL_ARTILLERY_BARRAGE",
	"SPECIAL_MISSILE_DEFENDER_LASER_GUIDED_MISSILES",
	"SPECIAL_REMOTE_CHARGES",
	"SPECIAL_TIMED_CHARGES",
	"SPECIAL_HACKER_DISABLE_BUILDING",
	"SPECIAL_TANKHUNTER_TNT_ATTACK",
	"SPECIAL_BLACKLOTUS_CAPTURE_BUILDING",
	"SPECIAL_MAN_THE_WALLS",
	"SPECIAL_OSGILIATH_VETERANS",
	"SPECIAL_INFANTRY_CAPTURE_BUILDING",
	"SPECIAL_RADAR_VAN_SCAN",
	"SPECIAL_SPY_DRONE",
	"SPECIAL_DISGUISE_AS_VEHICLE",
	"SPECIAL_REPAIR_VEHICLES",
	"SPECIAL_PARTICLE_UPLINK_CANNON",
	"SPECIAL_RANGER_AMBUSH",
	"SPECIAL_CHANGE_BATTLE_PLANS",
	"SPECIAL_CIA_INTELLIGENCE",
	"SPECIAL_CLEANUP_AREA",
	"SPECIAL_GRAB_PASSENGER",
	"SPECIAL_GRAB_CHUNK",
	"SPECIAL_SPAWN_ORCS",
	"SPECIAL_CHARGE_ATTACK",
	"SPECIAL_PART_THE_HEAVENS",
	"SPECIAL_DEFLECT_PROJECTILES",
	"SPECIAL_SIEGEDEPLOY",
	"SPECIAL_STOP",
	"SPECIAL_ARROW_STORM",
	"SPECIAL_SWOOP_ATTACK",
	"SPECIAL_LEVEL_ATTACK",
	"SPECIAL_LEVEL_POSITION",
	"SPECIAL_GIVE_UPGRADE",
	"SPECIAL_ROUSING_SPEECH",
	"SPECIAL_GENERAL_TARGETLESS",
	"SPECIAL_GENERAL_TARGETLESS_TWO",
	"SPECIAL_SHIELD_BUBBLE",
	"SPECIAL_TOGGLE_MOUNTED",
	"SPECIAL_WIZARD_BLAST",
	"SPECIAL_GLORIOUS_CHARGE",
	"SPECIAL_WOUND_ARROW",
	"SPECIAL_HERO_MODE",
	"SPECIAL_FLAMING_SWORD",
	"SPECIAL_FIRE_WHIP",
	"SPECIAL_BALROG_BREATH",
	"SPECIAL_MTTROLL_BORED",
	"SPECIAL_BALROG_WINGS",
	"SPECIAL_BALROG_SCREAM",
	"SPECIAL_TRAINING",
	"SPECIAL_TELEKENETIC_PUSH",
	"SPECIAL_SONIC_SONG",
	"SPECIAL_REVEAL_MAP_AREA",
	"SPECIAL_KNIFE_ATTACK",
	"SPECIAL_SPAWN_OATHBREAKERS",
	"SPECIAL_CALL_OF_THE_DEEP",
	"SPECIAL_SKULL_TOTEM",
	"SPECIAL_EXTINGUISH_FIRE",
	"SPECIAL_TRIGGER_ATTRIBUTE_MODIFIER",
	"SPECIAL_DOMINATE_ENEMY",
	"SPECIAL_WORD_OF_POWER",
	"SPECIAL_KNIFE_FIGHTER",
	"SPECIAL_SPELL_BOOK_HEAL",
	"SPECIAL_SPELL_BOOK_ELVEN_GIFTS",
	"SPECIAL_SPELL_BOOK_SPAWN_LONE_TOWER",
	"SPECIAL_SPELL_BOOK_ENSHROUDING_MIST",
	"SPECIAL_SPELL_BOOK_RALLYING_CALL",
	"SPECIAL_SPELL_BOOK_TOM_BOMBADIL",
	"SPECIAL_SPELL_BOOK_HOBBIT_ALLIES",
	"SPECIAL_SPELL_BOOK_REBUILD",
	"SPECIAL_SPELL_BOOK_ARROW_VOLLEY_GOOD",
	"SPECIAL_SPELL_BOOK_ELVEN_WOOD",
	"SPECIAL_SPELL_BOOK_DWARVEN_RICHES",
	"SPECIAL_SPELL_BOOK_MEN_OF_DALE_ALLIES",
	"SPECIAL_SPELL_BOOK_CLOUD_BREAK",
	"SPECIAL_SPELL_BOOK_ROHAN_ALLIES",
	"SPECIAL_SPELL_BOOK_DUNEDAIN_ALLIES",
	"SPECIAL_SPELL_BOOK_ENT_ALLIES",
	"SPECIAL_SPELL_BOOK_EAGLE_ALLIES",
	"SPECIAL_SPELL_BOOK_UNDERMINE",
	"SPECIAL_SPELL_BOOK_BOMBARD",
	"SPECIAL_SPELL_BOOK_ARMY_OF_THE_DEAD",
	"SPECIAL_SPELL_BOOK_EARTHQUAKE",
	"SPECIAL_SPELL_BOOK_FLOOD",
	"SPECIAL_SPELL_BOOK_SUNFLARE",
	"SPECIAL_SPELL_BOOK_CITADEL",
	"SPECIAL_SPELL_BOOK_TAINT",
	"SPECIAL_SPELL_BOOK_EYE_OF_SAURON",
	"SPECIAL_SPELL_BOOK_BARRICADE",
	"SPECIAL_SPELL_BOOK_WAR_CHANT",
	"SPECIAL_SPELL_BOOK_PALANTIR_VISION",
	"SPECIAL_SPELL_BOOK_CREBAIN",
	"SPECIAL_SPELL_BOOK_CAVE_BATS",
	"SPECIAL_SPELL_BOOK_INDUSTRY",
	"SPECIAL_SPELL_BOOK_DEVASTATION",
	"SPECIAL_SPELL_BOOK_UNTAMED_ALLEGIANCE",
	"SPECIAL_SPELL_BOOK_ARROW_VOLLEY_EVIL",
	"SPECIAL_SPELL_BOOK_WILD_MEN_ALLIES",
	"SPECIAL_SPELL_BOOK_SCAVENGER",
	"SPECIAL_SPELL_BOOK_CALL_THE_HORDE",
	"SPECIAL_SPELL_BOOK_SPIDERLING_ALLIES",
	"SPECIAL_SPELL_BOOK_DARKNESS",
	"SPECIAL_SPELL_BOOK_AWAKEN_WYRM",
	"SPECIAL_SPELL_BOOK_FREEZING_RAIN",
	"SPECIAL_SPELL_BOOK_FUEL_THE_FIRES",
	"SPECIAL_SPELL_BOOK_WATCHER_ALLY",
	"SPECIAL_SPELL_BOOK_BALROG_ALLY",
	"SPECIAL_SPELL_BOOK_RAIN_OF_FIRE",
	"SPECIAL_SPELL_BOOK_DRAGON_ALLY",
	"SPECIAL_SPELL_BOOK_DRAGON_STRIKE",
	"SPECIAL_ATHELAS",
	"SPECIAL_AT_VISIBLE_OBJECT",
	"SPECIAL_SARUMAN_FIRE_BALL",
	"SPECIAL_DISGUISE",
	"SPECIAL_SMITE_CANCELDISGUISE",
	"SPECIAL_ATTRIBUTEMOD_CANCELDISGUISE",
	"SPECIAL_KINGS_FAVOR",
	"SPECIAL_FAKE_LEADERSHIP_BUTTON",
	"SPECIAL_GIVE_UPGRADE_NEAREST",
	"SPECIAL_SCREECH",
	"SPECIAL_REPAIR_STRUCTURE",
	"SPECIAL_EAT",
	"SPECIAL_GIMLI_LEAP",
	"SPECIAL_HARVEST",
	"SPECIAL_PERSONAL_FLOOD",
	"SPECIAL_ELVEN_GRACE",
	"SPECIAL_AT_VISIBLE_GROUNDED_OBJECT",
	"SPECIAL_TELEPORT_TEAM_TO_CASTER",
	"SPECIAL_SPAWN_TORNADO",
	"SPECIAL_CURSE_ENEMY",
	"SPECIAL_STORE_LIST_1",
	"SPECIAL_STORE_LIST_2",
	"SPECIAL_TELEPORT_LIST_TO_POSITION",
	"SPECIAL_EVACUATE_GARRISON",
	"SPECIAL_GENERAL_TARGETLESS_THREE",
	"SPECIAL_SUMMON_ALLIES",
};

template <size_t NUMBITS>
class BitFlags
{
public:
	static Int getSingleBitFromName( const char *token );

private:
	_STL::bitset<NUMBITS> m_bits;
};

template <size_t NUMBITS>
Int BitFlags<NUMBITS>::getSingleBitFromName( const char *token )
{
	Int i = 0;
	for ( const char *const *name = SpecialPowerNames; *name; ++name, ++i )
	{
		if ( _strcmpi( *name, token ) == 0 )
			return i;
	}
	return -1;
}

// ?getSingleBitFromName@?$BitFlags@$0JK@@@SAHPBD@Z
template Int BitFlags<154>::getSingleBitFromName( const char *token );
