// cl: /O1 /GX /MD /D_CRTIMP= /D_STLP_USE_STATIC_LIB /Ireference/shims/bfmealloc
// stlport
#include <vector>
// Generated by build/mg/famgen.py (vecdtor): same-shape family members.

// ??1?$vector@VRva00297360Element@@V?$allocator@VRva00297360Element@@@_STL@@@_STL@@QAE@XZ @0x403960
class Rva00297360Element { public: ~Rva00297360Element(); };
template _STL::vector<Rva00297360Element>::~vector();
