// cl: /O2 /MD
// Each class is declared locally only so its deleting destructor is emitted;
// the complete destructor call resolves through that destructor's own row.
// Generated by build/mg/famgen.py (gdtor30): same-shape family members.

// ??_GDX8FVFCategoryContainer@@UAEPAXI@Z @0x1461e0
class DX8FVFCategoryContainer { public: __declspec(noinline) virtual ~DX8FVFCategoryContainer(); private: int m_famgen; };
DX8FVFCategoryContainer::~DX8FVFCategoryContainer() { m_famgen = 0; }
void famgenDelete(DX8FVFCategoryContainer *p) { delete p; }
