// cl: /MD
// Each class is declared locally only so its deleting destructor is emitted;
// the complete destructor call resolves through that destructor's own row.
// Generated by build/mg/famgen.py (gdtor): same-shape family members.

// ??_GArmorTemplate@@QAEPAXI@Z @0x1d8fe5
class ArmorTemplate { public: ~ArmorTemplate(); };
void famgenDelete(ArmorTemplate *p) { delete p; }

class Rva00255CD1
{
public:
	~Rva00255CD1();
};

class Rva00256641
{
public:
	void rva00256641();
};

void Rva00256641::rva00256641()
{
	((Rva00255CD1 *)this)->~Rva00255CD1();
}


// ??_GRva001DB3E0List@@QAEPAXI@Z @0x28ab16
class Rva001DB3E0List { public: ~Rva001DB3E0List(); };
void famgenDelete(Rva001DB3E0List *p) { delete p; }

// ??_GRva0048B95F@@QAEPAXI@Z @0x48b9b4
class Rva0048B95F { public: ~Rva0048B95F(); };
void famgenDelete(Rva0048B95F *p) { delete p; }

// ??_GLargeGroupBonusUpdateModuleData@@UAEPAXI@Z @0x490472
class LargeGroupBonusUpdateModuleData { public: __declspec(noinline) virtual ~LargeGroupBonusUpdateModuleData(); private: int m_famgen; };
LargeGroupBonusUpdateModuleData::~LargeGroupBonusUpdateModuleData() { m_famgen = 0; }
void famgenDelete(LargeGroupBonusUpdateModuleData *p) { delete p; }

// ??_GDamageFieldUpdate@@UAEPAXI@Z @0x4912fa
class DamageFieldUpdate { public: __declspec(noinline) virtual ~DamageFieldUpdate(); private: int m_famgen; };
DamageFieldUpdate::~DamageFieldUpdate() { m_famgen = 0; }
void famgenDelete(DamageFieldUpdate *p) { delete p; }

// ??_GRousingSpeechUpdate@@UAEPAXI@Z @0x4acffd
class RousingSpeechUpdate { public: __declspec(noinline) virtual ~RousingSpeechUpdate(); private: int m_famgen; };
RousingSpeechUpdate::~RousingSpeechUpdate() { m_famgen = 0; }
void famgenDelete(RousingSpeechUpdate *p) { delete p; }

// ??_GGloriousChargeUpdate@@UAEPAXI@Z @0x4ad6f4
class GloriousChargeUpdate { public: __declspec(noinline) virtual ~GloriousChargeUpdate(); private: int m_famgen; };
GloriousChargeUpdate::~GloriousChargeUpdate() { m_famgen = 0; }
void famgenDelete(GloriousChargeUpdate *p) { delete p; }

// ??_GTransitionDamageFXModuleData@@UAEPAXI@Z @0x4ba6f9
class TransitionDamageFXModuleData { public: __declspec(noinline) virtual ~TransitionDamageFXModuleData(); private: int m_famgen; };
TransitionDamageFXModuleData::~TransitionDamageFXModuleData() { m_famgen = 0; }
void famgenDelete(TransitionDamageFXModuleData *p) { delete p; }

// ??_GXfer@@UAEPAXI@Z @0x60c8b1
class Xfer { public: __declspec(noinline) virtual ~Xfer(); private: int m_famgen; };
Xfer::~Xfer() { m_famgen = 0; }
void famgenDelete(Xfer *p) { delete p; }
