// cl: /O1 /MD
// Each class is declared locally only so its deleting destructor is emitted;
// the complete destructor call resolves through that destructor's own row.
// Generated by build/mg/famgen.py (gdtor): same-shape family members.

// ??_GRva003B448C@@QAEPAXI@Z @0x3b57bd
class Rva003B448C { public: ~Rva003B448C(); };
void famgenDelete(Rva003B448C *p) { delete p; }
