// cl: /MD
// Each class is declared locally only so its deleting destructor is emitted;
// the complete destructor call resolves through that destructor's own row.
// Generated by build/mg/famgen.py (gdtor): same-shape family members.

// ??_GGenericMultiListClass@@UAEPAXI@Z @0x6583c
class GenericMultiListClass { public: __declspec(noinline) virtual ~GenericMultiListClass(); private: int m_famgen; };
GenericMultiListClass::~GenericMultiListClass() { m_famgen = 0; }
void famgenDelete(GenericMultiListClass *p) { delete p; }

// ??_GAudioEventRTS@@QAEPAXI@Z @0xb99f2
class AudioEventRTS { public: ~AudioEventRTS(); };
void famgenDelete(AudioEventRTS *p) { delete p; }

// ??_GHTreeClass@@QAEPAXI@Z @0x17fadf
class HTreeClass { public: ~HTreeClass(); };
void famgenDelete(HTreeClass *p) { delete p; }

// ??_GHLodDefClass@@QAEPAXI@Z @0x17fea5
class HLodDefClass { public: ~HLodDefClass(); };
void famgenDelete(HLodDefClass *p) { delete p; }

// ??_GArmorTemplate@@QAEPAXI@Z @0x1d8fe5
class ArmorTemplate { public: ~ArmorTemplate(); };
void famgenDelete(ArmorTemplate *p) { delete p; }

// ??_GVersionBlockEntry@@QAEPAXI@Z @0x2385c1
class VersionBlockEntry { public: ~VersionBlockEntry(); };
void famgenDelete(VersionBlockEntry *p) { delete p; }

// ??_GCrushDieModuleData@@UAEPAXI@Z @0x255097
class CrushDieModuleData { public: __declspec(noinline) virtual ~CrushDieModuleData(); private: int m_famgen; };
CrushDieModuleData::~CrushDieModuleData() { m_famgen = 0; }
void famgenDelete(CrushDieModuleData *p) { delete p; }

// ??_GBfmeStringRecord002CF550@@QAEPAXI@Z @0x256625
class BfmeStringRecord002CF550 { public: ~BfmeStringRecord002CF550(); };
void famgenDelete(BfmeStringRecord002CF550 *p) { delete p; }

class Rva00255CD1
{
public:
	~Rva00255CD1();
};

class Rva00256641
{
public:
	void rva00256641();
};

void Rva00256641::rva00256641()
{
	((Rva00255CD1 *)this)->~Rva00255CD1();
}


// ??_GUnicodeString@@QAEPAXI@Z @0x2605cf
class UnicodeString { public: ~UnicodeString(); };
void famgenDelete(UnicodeString *p) { delete p; }

// ??_GCameraMarker@@QAEPAXI@Z @0x288903
class CameraMarker { public: ~CameraMarker(); };
void famgenDelete(CameraMarker *p) { delete p; }

// ??_GRva001DB3E0List@@QAEPAXI@Z @0x28ab16
class Rva001DB3E0List { public: ~Rva001DB3E0List(); };
void famgenDelete(Rva001DB3E0List *p) { delete p; }

// ??_GProductionPrerequisite@@QAEPAXI@Z @0x2cf156
class ProductionPrerequisite { public: ~ProductionPrerequisite(); };
void famgenDelete(ProductionPrerequisite *p) { delete p; }

// ??_GRva002390CB@@QAEPAXI@Z @0x31b4ba
class Rva002390CB { public: ~Rva002390CB(); };
void famgenDelete(Rva002390CB *p) { delete p; }

// ??_GGen_004902A0@@UAEPAXI@Z @0x355fa5
class Gen_004902A0 { public: __declspec(noinline) virtual ~Gen_004902A0(); private: int m_famgen; };
Gen_004902A0::~Gen_004902A0() { m_famgen = 0; }
void famgenDelete(Gen_004902A0 *p) { delete p; }

// ??_GBfmeNodeValueEBD@@QAEPAXI@Z @0x382b47
class BfmeNodeValueEBD { public: ~BfmeNodeValueEBD(); };
void famgenDelete(BfmeNodeValueEBD *p) { delete p; }

// ??_GBfmeOpaqueOwnedRecord492@@QAEPAXI@Z @0x38995c
class BfmeOpaqueOwnedRecord492 { public: ~BfmeOpaqueOwnedRecord492(); };
void famgenDelete(BfmeOpaqueOwnedRecord492 *p) { delete p; }

// ??_GBfmeOpaqueOwnedRecord840@@QAEPAXI@Z @0x38a588
class BfmeOpaqueOwnedRecord840 { public: ~BfmeOpaqueOwnedRecord840(); };
void famgenDelete(BfmeOpaqueOwnedRecord840 *p) { delete p; }

// ??_GRva00220240FlatDtor@@UAEPAXI@Z @0x466bcd
class Rva00220240FlatDtor { public: __declspec(noinline) virtual ~Rva00220240FlatDtor(); private: int m_famgen; };
Rva00220240FlatDtor::~Rva00220240FlatDtor() { m_famgen = 0; }
void famgenDelete(Rva00220240FlatDtor *p) { delete p; }

// ??_GRva0048B95F@@QAEPAXI@Z @0x48b9b4
class Rva0048B95F { public: ~Rva0048B95F(); };
void famgenDelete(Rva0048B95F *p) { delete p; }

// ??_GLargeGroupBonusUpdateModuleData@@UAEPAXI@Z @0x490472
class LargeGroupBonusUpdateModuleData { public: __declspec(noinline) virtual ~LargeGroupBonusUpdateModuleData(); private: int m_famgen; };
LargeGroupBonusUpdateModuleData::~LargeGroupBonusUpdateModuleData() { m_famgen = 0; }
void famgenDelete(LargeGroupBonusUpdateModuleData *p) { delete p; }

// ??_GDamageFieldUpdate@@UAEPAXI@Z @0x4912fa
class DamageFieldUpdate { public: __declspec(noinline) virtual ~DamageFieldUpdate(); private: int m_famgen; };
DamageFieldUpdate::~DamageFieldUpdate() { m_famgen = 0; }
void famgenDelete(DamageFieldUpdate *p) { delete p; }

// ??_GRousingSpeechUpdate@@UAEPAXI@Z @0x4acffd
class RousingSpeechUpdate { public: __declspec(noinline) virtual ~RousingSpeechUpdate(); private: int m_famgen; };
RousingSpeechUpdate::~RousingSpeechUpdate() { m_famgen = 0; }
void famgenDelete(RousingSpeechUpdate *p) { delete p; }

// ??_GGloriousChargeUpdate@@UAEPAXI@Z @0x4ad6f4
class GloriousChargeUpdate { public: __declspec(noinline) virtual ~GloriousChargeUpdate(); private: int m_famgen; };
GloriousChargeUpdate::~GloriousChargeUpdate() { m_famgen = 0; }
void famgenDelete(GloriousChargeUpdate *p) { delete p; }

// ??_GTransitionDamageFXModuleData@@UAEPAXI@Z @0x4ba6f9
class TransitionDamageFXModuleData { public: __declspec(noinline) virtual ~TransitionDamageFXModuleData(); private: int m_famgen; };
TransitionDamageFXModuleData::~TransitionDamageFXModuleData() { m_famgen = 0; }
void famgenDelete(TransitionDamageFXModuleData *p) { delete p; }

// ??_GRva0025A390FlatDtor@@UAEPAXI@Z @0x4c5535
class Rva0025A390FlatDtor { public: __declspec(noinline) virtual ~Rva0025A390FlatDtor(); private: int m_famgen; };
Rva0025A390FlatDtor::~Rva0025A390FlatDtor() { m_famgen = 0; }
void famgenDelete(Rva0025A390FlatDtor *p) { delete p; }

// ??_GUDPDrain@@QAEPAXI@Z @0x4d4b8b
class UDPDrain { public: ~UDPDrain(); };
void famgenDelete(UDPDrain *p) { delete p; }

// ??_GBfmePoolRef10@@QAEPAXI@Z @0x568e33
class BfmePoolRef10 { public: ~BfmePoolRef10(); };
void famgenDelete(BfmePoolRef10 *p) { delete p; }

// ??_GMapMetaData@@QAEPAXI@Z @0x57e03c
class MapMetaData { public: ~MapMetaData(); };
void famgenDelete(MapMetaData *p) { delete p; }

// ??_GPlayerPosition@@QAEPAXI@Z @0x59e991
class PlayerPosition { public: ~PlayerPosition(); };
void famgenDelete(PlayerPosition *p) { delete p; }

// ??_GBfmeContainerRecord005FDEC7@@QAEPAXI@Z @0x5f9406
class BfmeContainerRecord005FDEC7 { public: ~BfmeContainerRecord005FDEC7(); };
void famgenDelete(BfmeContainerRecord005FDEC7 *p) { delete p; }

// ??_GXfer@@UAEPAXI@Z @0x60c8b1
class Xfer { public: __declspec(noinline) virtual ~Xfer(); private: int m_famgen; };
Xfer::~Xfer() { m_famgen = 0; }
void famgenDelete(Xfer *p) { delete p; }
