// cl: /O1 /MD
// Each class is declared locally only so its deleting destructor is emitted;
// the complete destructor call resolves through that destructor's own row.
// Generated by build/mg/famgen.py (gdtor): same-shape family members.

// ??_GRva003F610FElement@@QAEPAXI@Z @0x3f5530
class Rva003F610FElement { public: ~Rva003F610FElement(); };
void famgenDelete(Rva003F610FElement *p) { delete p; }

// ??_GRva00520211Element@@QAEPAXI@Z @0x51fc86
class Rva00520211Element { public: ~Rva00520211Element(); };
void famgenDelete(Rva00520211Element *p) { delete p; }
