// cl: /O1 /MD
// Each class is declared locally only so its deleting destructor is emitted;
// the complete destructor call resolves through that destructor's own row.
// Generated by build/mg/famgen.py (gdtor): same-shape family members.

// ??_GW3DLightDrawModuleData@@UAEPAXI@Z @0xcfddf
class W3DLightDrawModuleData { public: __declspec(noinline) virtual ~W3DLightDrawModuleData(); private: int m_famgen; };
W3DLightDrawModuleData::~W3DLightDrawModuleData() { m_famgen = 0; }
void famgenDelete(W3DLightDrawModuleData *p) { delete p; }
