// cl: /GX /MD /D_CRTIMP= /D_STLP_USE_STATIC_LIB /Ireference/shims/bfmealloc
// stlport
#include <vector>
// Generated by build/mg/famgen.py (vecdtor): same-shape family members.
// This 0x10-byte element and CameraMarker both have their AsciiString at +4;
// either destructor releases only that StringBase member. The Rva pin records
// the same ICF twin address, 0x0029D7C2, as the matched CameraMarker dtor.
// Keep the vector<T> body unchanged and bind its element-dtor reference here.
#pragma comment(linker, "/alternatename:??1Rva00297360Element@@QAE@XZ=??1CameraMarker@@QAE@XZ")

// ??1?$vector@VRva00297360Element@@V?$allocator@VRva00297360Element@@@_STL@@@_STL@@QAE@XZ @0x403960
class Rva00297360Element { public: ~Rva00297360Element(); };
template _STL::vector<Rva00297360Element>::~vector();
