// cl: /O1 /MD
// Each class is declared locally only so its deleting destructor is emitted;
// the complete destructor call resolves through that destructor's own row.
// Generated by build/mg/famgen.py (gdtor): same-shape family members.

// ??_GBfmeStringTailRecord144@@QAEPAXI@Z @0x51b6d
class BfmeStringTailRecord144 { public: ~BfmeStringTailRecord144(); };
void famgenDelete(BfmeStringTailRecord144 *p) { delete p; }

// ??_GRadiusDecal@@QAEPAXI@Z @0xd1687
class RadiusDecal { public: ~RadiusDecal(); };
void famgenDelete(RadiusDecal *p) { delete p; }

// ??_GBfmeStringTailRecord156@@QAEPAXI@Z @0x1d99cb
class BfmeStringTailRecord156 { public: ~BfmeStringTailRecord156(); };
void famgenDelete(BfmeStringTailRecord156 *p) { delete p; }

// ??_GPath@@QAEPAXI@Z @0x262895
class Path { public: ~Path(); };
void famgenDelete(Path *p) { delete p; }

// ??_GGeometryShape@@QAEPAXI@Z @0x2af4d1
class GeometryShape { public: ~GeometryShape(); };
void famgenDelete(GeometryShape *p) { delete p; }

// ??_GBfmeStringHeadRecord148@@QAEPAXI@Z @0x3611d3
class BfmeStringHeadRecord148 { public: ~BfmeStringHeadRecord148(); };
void famgenDelete(BfmeStringHeadRecord148 *p) { delete p; }

// ??_GBfmeNodeZ@@QAEPAXI@Z @0x3b4470
class BfmeNodeZ { public: ~BfmeNodeZ(); };
void famgenDelete(BfmeNodeZ *p) { delete p; }

// ??_GBfmeStringRecord00111ACF@@QAEPAXI@Z @0x3f63e5
class BfmeStringRecord00111ACF { public: ~BfmeStringRecord00111ACF(); };
void famgenDelete(BfmeStringRecord00111ACF *p) { delete p; }

// ??_GRva00360D26Member@@QAEPAXI@Z @0x421728
class Rva00360D26Member { public: ~Rva00360D26Member(); };
void famgenDelete(Rva00360D26Member *p) { delete p; }

// ??_GBfmeObject544@@QAEPAXI@Z @0x4cacfb
class BfmeObject544 { public: ~BfmeObject544(); };
void famgenDelete(BfmeObject544 *p) { delete p; }

// ??_GGen_001DB2C0@@QAEPAXI@Z @0x4de5f4
class Gen_001DB2C0 { public: ~Gen_001DB2C0(); };
void famgenDelete(Gen_001DB2C0 *p) { delete p; }

// ??_GBfmeOpaqueOwnedRecord1432@@QAEPAXI@Z @0x555b81
class BfmeOpaqueOwnedRecord1432 { public: ~BfmeOpaqueOwnedRecord1432(); };
void famgenDelete(BfmeOpaqueOwnedRecord1432 *p) { delete p; }

// ??_GBfmeOpaqueOwnedRecord1408@@QAEPAXI@Z @0x555b9d
class BfmeOpaqueOwnedRecord1408 { public: ~BfmeOpaqueOwnedRecord1408(); };
void famgenDelete(BfmeOpaqueOwnedRecord1408 *p) { delete p; }
