// cl: /O1 /MD
// Each class redeclares its protected virtual destructor and defines it locally,
// which emits the scalar deleting destructor in this TU; the dtor call inside
// resolves through that destructor's own row (same pattern as spec_gdtor).
// Generated by build/mg/famgen.py (gdtor_prot): same-shape family members.

// ??_GArmorUpgrade@@MAEPAXI@Z @0x004B3499
class ArmorUpgrade { protected: __declspec(noinline) virtual ~ArmorUpgrade(); private: int m_famgen;
  friend void famgenDelete(ArmorUpgrade *p); };
ArmorUpgrade::~ArmorUpgrade() { m_famgen = 0; }
void famgenDelete(ArmorUpgrade *p) { delete p; }
