// cl: /MD
// Each class is declared locally only so its deleting destructor is emitted;
// the complete destructor call resolves through that destructor's own row.
// Generated by build/mg/famgen.py (gdtor): same-shape family members.

// ??_GRva0022167C@@QAEPAXI@Z @0x0022168A 28B
// Deleting dtor calls rowed ??1Rva0022167C@@QAE@XZ plus operator delete.
// Evidence: retail bytes plus chain callee 0x0022167C plus vtable slot 0 of 0x007E6BA8.
class Rva0022167C { public: ~Rva0022167C(); };
void famgenDelete(Rva0022167C *p) { delete p; }
