// cl: /DNDEBUG /MD /EHa /Oy-
// Each class is declared locally only so its deleting destructor is emitted.
// Generated by build/mg/famgen.py (auto): same-shape family members.

// ??_GDebugIOCon@@UAEPAXI@Z @0x40e20
class DebugIOCon { public: __declspec(noinline) virtual ~DebugIOCon(); private: int m_famgen; };
DebugIOCon::~DebugIOCon() { m_famgen = 0; }
void famgenDelete(DebugIOCon *p) { delete p; }
