// cl: /O1 /MD
// Each class is declared locally only so its deleting destructor is emitted;
// the complete destructor call resolves through that destructor's own row.
// Generated by build/mg/famgen.py (gdtor): same-shape family members.

// ??_GRva0017FB94@@UAEPAXI@Z @0x17fd8b
class Rva0017FB94 { public: __declspec(noinline) virtual ~Rva0017FB94(); private: int m_famgen; };
Rva0017FB94::~Rva0017FB94() { m_famgen = 0; }
void famgenDelete(Rva0017FB94 *p) { delete p; }
