// cl: /O1 /G7 /arch:SSE /MD /EHsc /DNDEBUG
// Primary semantic guide: ZH GameLODManager::applyStaticLODLevel and BF1 575ba2 GameLODManagerApplyStaticLODLevel.cpp.
// BF2 native2022E9..2025AA carries a 76-byte preset and target-specific render refreshes.
// LODTextureReduction is the existing DB5FA0 selector read as lodLimit by fxshadersetup.
// LODMeshCacheSetting is the existing DEC410 byte; its observed role is the
// setting whose change invalidates the mesh cache. Both names describe target
// use, not recovered original symbol spellings. Provider definitions are shared.
typedef bool LODBool;
class GlobalData; extern GlobalData *TheWritableGlobalData;
struct LODPresetBFME2 {
 int particles;
 int processor;
 int maxParticles;
 LODBool shadowVolumes;
 LODBool shadowDecals;
 LODBool shadowsOff;
 char gapF[0x1];
 int minimumFps;
 LODBool cloud;
 LODBool light;
 char gap16[0x2];
 int sample;
 LODBool softWater;
 char gap1D[0x3];
 int trackEdges;
 int opaqueEdges;
 int fadeDelay;
 int option;
 LODBool treeSway;
 char gap31[0x3];
 int stream;
 int textureReduction;
 LODBool meshSetting;
 LODBool fpsLimit;
 char gap3E[0x2];
 int healthStyle;
 int opaque44;
 int opaque48;
};
struct LODGlobalDataView {
 char gap0[0x1C];
 LODBool field1C;
 char gap1D[0x7];
 LODBool field24;
 LODBool field25;
 char gap26[0x23];
 LODBool field49;
 LODBool field4A;
 char gap4B[0x13];
 LODBool field5E;
 char gap5F[0x1];
 LODBool field60;
 LODBool field61;
 LODBool field62;
 char gap63[0x21];
 LODBool field84;
 char gap85[0x8B];
 int field110;
 int field114;
 int field118;
 char gap11C[0x889];
 LODBool field9A5;
 char gap9A6[0x1];
 LODBool field9A7;
 char gap9A8[0x16];
 LODBool field9BE;
 char gap9BF[0x109];
 int fieldAC8;
 char gapACC[0x24];
 LODBool fieldAF0;
 LODBool fieldAF1;
};
#define GD ((LODGlobalDataView*)TheWritableGlobalData)
class OptionPreferences {public: OptionPreferences();virtual ~OptionPreferences();bool getAllHealthBars();char storage[16];};
class GameClient;extern GameClient *TheGameClient;
class LODClientSlots {public:
 virtual void slot0();
 virtual void slot1();
 virtual void slot2();
 virtual void slot3();
 virtual void slot4();
 virtual void slot5();
 virtual void slot6();
 virtual void slot7();
 virtual void slot8();
 virtual void slot9();
 virtual void slot10();
 virtual void slot11();
 virtual void slot12();
 virtual void slot13();
 virtual void slot14();
 virtual void slot15();
 virtual void slot16();
 virtual void slot17();
 virtual void slot18();
 virtual void slot19();
 virtual void slot20();
 virtual void slot21();
 virtual void slot22();
 virtual void slot23();
 virtual void slot24();
 virtual void slot25();
 virtual void slot26();
 virtual void slot27();
 virtual void slot28();
 virtual void slot29();
 virtual void slot30();
 virtual void slot31();
 virtual void slot32();
 virtual void slot33();
 virtual void slot34();
};
class BaseHeightMapRenderObjClass;extern BaseHeightMapRenderObjClass *TheTerrainRenderObject;
class LODTerrainSlots {public:
 virtual void slot0();
 virtual void slot1();
 virtual void slot2();
 virtual void slot3();
 virtual void slot4();
 virtual void slot5();
 virtual void slot6();
 virtual void slot7();
 virtual void slot8();
 virtual void slot9();
 virtual void slot10();
 virtual void slot11();
 virtual void slot12();
 virtual void slot13();
 virtual void slot14();
 virtual void slot15();
 virtual void slot16();
 virtual void slot17();
 virtual void slot18();
 virtual void slot19();
 virtual void slot20();
 virtual void slot21();
 virtual void slot22();
 virtual void slot23();
 virtual void slot24();
 virtual void slot25();
 virtual void slot26();
 virtual void slot27();
 virtual void slot28();
 virtual void slot29();
 virtual void slot30();
 virtual void slot31();
 virtual void slot32();
 virtual void slot33();
 virtual void slot34();
 virtual void slot35();
 virtual void slot36();
 virtual void slot37();
 virtual void slot38();
 virtual void slot39();
 virtual void slot40();
 virtual void slot41();
 virtual void slot42();
 virtual void slot43();
 virtual void slot44();
 virtual void slot45();
 virtual void slot46();
 virtual void slot47();
 virtual void slot48();
 virtual void slot49();
 virtual void slot50();
 virtual void slot51();
 virtual void slot52();
 virtual void slot53();
 virtual void slot54();
 virtual void slot55();
 virtual void slot56();
 virtual void slot57();
 virtual void slot58();
 virtual void slot59();
 virtual void slot60();
 virtual void slot61();
 virtual void slot62();
 virtual void slot63();
 virtual void slot64();
 virtual void slot65();
 virtual void slot66();
 virtual void slot67();
 virtual void slot68();
 virtual void slot69();
 virtual void slot70();
 virtual void slot71();
 virtual void slot72();
 virtual void slot73();
 virtual void slot74();
 virtual void slot75();
 virtual void slot76();
 virtual void slot77();
 virtual void slot78();
 virtual void slot79();
 virtual void slot80();
 virtual void slot81();
 virtual void slot82();
 virtual void slot83();
 virtual void slot84();
 virtual void slot85();
 virtual void slot86();
 virtual void slot87();
 virtual void slot88();
 virtual void slot89();
 virtual void slot90();
 virtual void slot91();
 virtual void slot92();
 virtual void slot93();
 virtual void slot94();
 virtual void slot95();
 virtual void slot96();
 virtual void slot97();
 virtual void slot98();
 virtual void slot99();
 virtual void slot100();
 virtual void slot101();
 virtual void slot102();
 virtual void slot103();
 virtual void slot104();
 virtual void slot105();
 virtual void slot106();
 virtual void slot107();
 virtual void slot108();
 virtual void slot109();
 virtual void slot110();
 virtual void slot111();
 virtual void slot112();
 virtual void slot113();
 virtual void slot114();
 virtual void slot115();
 virtual void slot116();
 virtual void slot117();
 virtual void slot118();
 virtual void slot119();
 virtual void slot120();
 virtual void slot121();
 virtual void slot122();
 virtual void slot123();
 virtual void slot124();
 virtual void slot125();
 virtual void slot126();
 virtual void slot127();
 virtual void slot128();
 virtual void slot129();
 virtual void slot130();
};
class G00DFF080Obj; extern G00DFF080Obj *g_00DFF080;
class LODPostSlots {public:
 virtual void slot0();
 virtual void slot1();
 virtual void slot2();
 virtual void slot3();
 virtual void slot4();
 virtual void slot5();
 virtual void slot6();
 virtual void slot7();
 virtual void slot8();
 virtual void slot9();
};
class Shell;extern Shell *TheShell;
class Rva0035C194 {public: bool rva0035C194(bool,bool);};
extern int LODTextureReduction;
extern unsigned char LODMeshCacheSetting;
void Rva00117BB0SetOption(int);void rva00117120();
class WW3D {public:static void _Invalidate_Mesh_Cache();};
void Rva0012641FClear();
class SimpleStreakRendererClass {public:static void Init(bool);};
void BFME_DX8_Thread_Lock();bool BFME_DX8_Thread_Assert();
struct LODRenderLock { LODRenderLock(){BFME_DX8_Thread_Lock();} ~LODRenderLock(){BFME_DX8_Thread_Assert();} };
class Rva00DFE144Globals {public: void rva002022E9(int);private: LODPresetBFME2 presets[6];char gap1C8[0x1774-0x1c8];int controlParticles,controlProcessor,controlMinimum,controlCloud,controlSamples,controlStreams;char gap178C[0x17a0-0x178c];int control44,control48;char gap17A8[2];LODBool usePresetOption;};
void Rva00DFE144Globals::rva002022E9(int level)
{
 const LODPresetBFME2 &info=presets[level];
 controlParticles=info.particles;controlProcessor=info.processor;controlSamples=info.sample;controlStreams=info.stream;
 GD->field9A5=info.healthStyle>0;GD->field9A7=info.healthStyle<2;
 if(!GD->field9A5)GD->field9BE=1;
 else {OptionPreferences preferences;GD->field9BE=preferences.getAllHealthBars();}
 GD->field25=info.fpsLimit;GD->fieldAC8=info.maxParticles;controlMinimum=info.minimumFps;
 GD->field60=info.shadowVolumes;GD->field61=info.shadowDecals;GD->field62=info.shadowsOff;
 if(GD->field62){GD->field60=0;GD->field61=0;}
 int option=info.option;
 if(!usePresetOption)option=presets[0].option;
 Rva00117BB0SetOption(option);
 if(LODTextureReduction!=info.textureReduction){LODTextureReduction=info.textureReduction;if(TheGameClient)rva00117120();}
 if(LODMeshCacheSetting!=info.meshSetting){LODMeshCacheSetting=info.meshSetting;if(!TheGameClient)goto after_client;WW3D::_Invalidate_Mesh_Cache();}
 if(TheGameClient){
  ((LODClientSlots*)TheGameClient)->slot33();((LODClientSlots*)TheGameClient)->slot34();
  Rva0012641FClear();SimpleStreakRendererClass::Init(GD->field62);
 }
 after_client:
 GD->field49=info.cloud;GD->field4A=info.light;
 controlCloud=GD->field49?2:(GD->field4A!=0);
 GD->field5E=info.sample>=2;GD->field84=info.softWater;
 GD->field110=info.trackEdges;GD->field114=info.opaqueEdges;GD->field118=info.fadeDelay;
 GD->field24=info.particles<=0;GD->field1C=info.treeSway;
 control44=info.opaque44;control48=info.opaque48;
 if(TheTerrainRenderObject){LODRenderLock lock;((LODTerrainSlots*)TheTerrainRenderObject)->slot129();((LODTerrainSlots*)TheTerrainRenderObject)->slot130();}
 if(g_00DFF080)((LODPostSlots*)g_00DFF080)->slot9();
 GD->fieldAF0=controlProcessor>1&&!GD->fieldAF1;
 if(TheShell)((Rva0035C194*)TheShell)->rva0035C194(true,true);
}
