// cl: /GX- /MD /DNDEBUG
//
// ?rva004DF2E2@Rva004DF2E2@@QAEXXZ @0x004DF2E2 13B.
// Sets DECK_HEIGHT_OFFSET (0x1d) to true on the Object at this+8 via rowed
// Object::setStatus 0x0023DB0E. Evidence: push 1 push 0x1d match the
// ObjectStatusTypes order (29 equals DECK_HEIGHT_OFFSET) and Bool true;
// caller at 0x004DF3EF passes its own this (esi) with no stack args; First at
// +0x8 proves the Object* member. Copies the next TU Rva004DF324Dtor flags.
enum ObjectStatusTypes
{
	OBJECT_STATUS_NONE,
	OBJECT_STATUS_DESTROYED,
	OBJECT_STATUS_CAN_ATTACK,
	OBJECT_STATUS_UNDER_CONSTRUCTION,
	OBJECT_STATUS_UNSELECTABLE,
	OBJECT_STATUS_NO_COLLISIONS,
	OBJECT_STATUS_NO_ATTACK,
	OBJECT_STATUS_AIRBORNE_TARGET,
	OBJECT_STATUS_PARACHUTING,
	OBJECT_STATUS_REPULSOR,
	OBJECT_STATUS_HIJACKED,
	OBJECT_STATUS_AFLAME,
	OBJECT_STATUS_BURNED,
	OBJECT_STATUS_WET,
	OBJECT_STATUS_IS_FIRING_WEAPON,
	OBJECT_STATUS_BRAKING,
	OBJECT_STATUS_STEALTHED,
	OBJECT_STATUS_DETECTED,
	OBJECT_STATUS_CAN_STEALTH,
	OBJECT_STATUS_SOLD,
	OBJECT_STATUS_UNDERGOING_REPAIR,
	OBJECT_STATUS_RECONSTRUCTING,
	OBJECT_STATUS_MASKED,
	OBJECT_STATUS_IS_ATTACKING,
	OBJECT_STATUS_IS_USING_ABILITY,
	OBJECT_STATUS_IS_AIMING_WEAPON,
	OBJECT_STATUS_NO_ATTACK_FROM_AI,
	OBJECT_STATUS_IGNORING_STEALTH,
	OBJECT_STATUS_IS_CARBOMB,
	OBJECT_STATUS_DECK_HEIGHT_OFFSET,
	OBJECT_STATUS_COUNT
};

class Object
{
public:
	void setStatus(ObjectStatusTypes bit, bool flag);
};

class Rva004DF2E2
{
private:
	char m_pad[8];
	Object *m_obj08; // +0x08
public:
	void rva004DF2E2();
	void rva004DF2EF();
};

void Rva004DF2E2::rva004DF2E2()
{
	m_obj08->setStatus(OBJECT_STATUS_DECK_HEIGHT_OFFSET, true);
}

// @0x004DF2EF 13B. Clears DECK_HEIGHT_OFFSET (0x1d) to false on the same
// Object at this+8 via rowed setStatus; caller at 0x004DF31B passes its own
// this with no stack args; twin of rva004DF2E2 differing only by Bool false.
void Rva004DF2E2::rva004DF2EF()
{
	m_obj08->setStatus(OBJECT_STATUS_DECK_HEIGHT_OFFSET, false);
}
