// cl: /DNDEBUG /MD /EHsc
// Generated by: python3 tools/gen_uw.py land
// Do not edit by hand -- regenerate. Every row in this file is anchored to a
// compiler-local $L label, so inserting or removing anything renumbers the
// labels and breaks rows whose funclet bytes never changed.
//
// Each body exists to make MSVC emit one unwind funclet that retail also emits.
// The payloads are anonymous by design -- a frame slot and a destructor call,
// never a class identity -- and every callee address is read out of the retail
// funclet and pinned in reverse/symbols.csv, so the bytes prove the target.

void gen_uw_ext();
void gen_uw_sink(void *);

struct Gen_uw_0048ba39 { int m; ~Gen_uw_0048ba39(); };

void gen_uw_p15_0048ba39(Gen_uw_0048ba39 a0, Gen_uw_0048ba39 a1, Gen_uw_0048ba39 a2, Gen_uw_0048ba39 a3, Gen_uw_0048ba39 a4, Gen_uw_0048ba39 a5, Gen_uw_0048ba39 a6, Gen_uw_0048ba39 a7, Gen_uw_0048ba39 a8, Gen_uw_0048ba39 a9, Gen_uw_0048ba39 a10, Gen_uw_0048ba39 a11, Gen_uw_0048ba39 a12, Gen_uw_0048ba39 a13, Gen_uw_0048ba39 a14) { gen_uw_ext(); }
