// cl: /DNDEBUG /MD /EHsc
// Generated by: python3 tools/gen_uw.py land
// Do not edit by hand -- regenerate. Every row in this file is anchored to a
// compiler-local $L label, so inserting or removing anything renumbers the
// labels and breaks rows whose funclet bytes never changed.
//
// Each body exists to make MSVC emit one unwind funclet that retail also emits.
// The payloads are anonymous by design -- a frame slot and a destructor call,
// never a class identity -- and every callee address is read out of the retail
// funclet and pinned in reverse/symbols.csv, so the bytes prove the target.

void gen_uw_ext();
void gen_uw_sink(void *);

struct Gen_uw_0049c38a { int m; ~Gen_uw_0049c38a(); };
struct Gen_uw_004c9f38 { int m; ~Gen_uw_004c9f38(); };
struct Gen_uw_004cacb8 { int m; ~Gen_uw_004cacb8(); };
struct Gen_uw_004e1416 { int m; ~Gen_uw_004e1416(); };
struct Gen_uw_004e14e1 { int m; ~Gen_uw_004e14e1(); };
struct Gen_uw_004e156b { int m; ~Gen_uw_004e156b(); };
struct Gen_uw_004e18a2 { int m; ~Gen_uw_004e18a2(); };
struct Gen_uw_004e194e { int m; ~Gen_uw_004e194e(); };
struct Gen_uw_004e1b72 { int m; ~Gen_uw_004e1b72(); };
struct Gen_uw_004e32f2 { int m; ~Gen_uw_004e32f2(); };
struct Gen_uw_004f5115 { int m; ~Gen_uw_004f5115(); };
struct Gen_uw_0050c283 { int m; ~Gen_uw_0050c283(); };
struct Gen_uw_0050c4e8 { int m; ~Gen_uw_0050c4e8(); };
struct Gen_uw_0052af77 { int m; ~Gen_uw_0052af77(); };
struct Gen_uw_00535776 { int m; ~Gen_uw_00535776(); };
struct Gen_uw_0054f508 { int m; ~Gen_uw_0054f508(); };
struct Gen_uw_005596ea { int m; ~Gen_uw_005596ea(); };
struct Gen_uw_0055a614 { int m; ~Gen_uw_0055a614(); };
struct Gen_uw_00577998 { int m; ~Gen_uw_00577998(); };
struct Gen_uw_005b804e { int m; ~Gen_uw_005b804e(); };

void gen_uw_l160_0049c38a()
{
	char pad[160]; gen_uw_sink(pad);
	Gen_uw_0049c38a v; gen_uw_ext();
}

void gen_uw_l164_0049c38a()
{
	char pad[164]; gen_uw_sink(pad);
	Gen_uw_0049c38a v; gen_uw_ext();
}

void gen_uw_l168_0049c38a()
{
	char pad[168]; gen_uw_sink(pad);
	Gen_uw_0049c38a v; gen_uw_ext();
}

void gen_uw_l172_0049c38a()
{
	char pad[172]; gen_uw_sink(pad);
	Gen_uw_0049c38a v; gen_uw_ext();
}

void gen_uw_l176_0049c38a()
{
	char pad[176]; gen_uw_sink(pad);
	Gen_uw_0049c38a v; gen_uw_ext();
}

void gen_uw_l180_0049c38a()
{
	char pad[180]; gen_uw_sink(pad);
	Gen_uw_0049c38a v; gen_uw_ext();
}

void gen_uw_l184_0049c38a()
{
	char pad[184]; gen_uw_sink(pad);
	Gen_uw_0049c38a v; gen_uw_ext();
}

void gen_uw_l188_0049c38a()
{
	char pad[188]; gen_uw_sink(pad);
	Gen_uw_0049c38a v; gen_uw_ext();
}

void gen_uw_l192_0049c38a()
{
	char pad[192]; gen_uw_sink(pad);
	Gen_uw_0049c38a v; gen_uw_ext();
}

void gen_uw_l196_0049c38a()
{
	char pad[196]; gen_uw_sink(pad);
	Gen_uw_0049c38a v; gen_uw_ext();
}

void gen_uw_l200_0049c38a()
{
	char pad[200]; gen_uw_sink(pad);
	Gen_uw_0049c38a v; gen_uw_ext();
}

void gen_uw_l204_0049c38a()
{
	char pad[204]; gen_uw_sink(pad);
	Gen_uw_0049c38a v; gen_uw_ext();
}

void gen_uw_l208_0049c38a()
{
	char pad[208]; gen_uw_sink(pad);
	Gen_uw_0049c38a v; gen_uw_ext();
}

void gen_uw_l212_0049c38a()
{
	char pad[212]; gen_uw_sink(pad);
	Gen_uw_0049c38a v; gen_uw_ext();
}

void gen_uw_l216_0049c38a()
{
	char pad[216]; gen_uw_sink(pad);
	Gen_uw_0049c38a v; gen_uw_ext();
}

void gen_uw_l220_0049c38a()
{
	char pad[220]; gen_uw_sink(pad);
	Gen_uw_0049c38a v; gen_uw_ext();
}

void gen_uw_l228_0049c38a()
{
	char pad[228]; gen_uw_sink(pad);
	Gen_uw_0049c38a v; gen_uw_ext();
}

void gen_uw_l232_0049c38a()
{
	char pad[232]; gen_uw_sink(pad);
	Gen_uw_0049c38a v; gen_uw_ext();
}

void gen_uw_l236_0049c38a()
{
	char pad[236]; gen_uw_sink(pad);
	Gen_uw_0049c38a v; gen_uw_ext();
}

void gen_uw_l240_0049c38a()
{
	char pad[240]; gen_uw_sink(pad);
	Gen_uw_0049c38a v; gen_uw_ext();
}

void gen_uw_l248_0049c38a()
{
	char pad[248]; gen_uw_sink(pad);
	Gen_uw_0049c38a v; gen_uw_ext();
}

void gen_uw_l256_0049c38a()
{
	char pad[256]; gen_uw_sink(pad);
	Gen_uw_0049c38a v; gen_uw_ext();
}

void gen_uw_l260_0049c38a()
{
	char pad[260]; gen_uw_sink(pad);
	Gen_uw_0049c38a v; gen_uw_ext();
}

void gen_uw_l268_0049c38a()
{
	char pad[268]; gen_uw_sink(pad);
	Gen_uw_0049c38a v; gen_uw_ext();
}

void gen_uw_l272_0049c38a()
{
	char pad[272]; gen_uw_sink(pad);
	Gen_uw_0049c38a v; gen_uw_ext();
}

void gen_uw_l280_0049c38a()
{
	char pad[280]; gen_uw_sink(pad);
	Gen_uw_0049c38a v; gen_uw_ext();
}

void gen_uw_l292_0049c38a()
{
	char pad[292]; gen_uw_sink(pad);
	Gen_uw_0049c38a v; gen_uw_ext();
}

void gen_uw_l308_0049c38a()
{
	char pad[308]; gen_uw_sink(pad);
	Gen_uw_0049c38a v; gen_uw_ext();
}

void gen_uw_l324_0049c38a()
{
	char pad[324]; gen_uw_sink(pad);
	Gen_uw_0049c38a v; gen_uw_ext();
}

void gen_uw_l340_0049c38a()
{
	char pad[340]; gen_uw_sink(pad);
	Gen_uw_0049c38a v; gen_uw_ext();
}

void gen_uw_l388_0049c38a()
{
	char pad[388]; gen_uw_sink(pad);
	Gen_uw_0049c38a v; gen_uw_ext();
}

void gen_uw_l452_0049c38a()
{
	char pad[452]; gen_uw_sink(pad);
	Gen_uw_0049c38a v; gen_uw_ext();
}

void gen_uw_l496_0049c38a()
{
	char pad[496]; gen_uw_sink(pad);
	Gen_uw_0049c38a v; gen_uw_ext();
}

void gen_uw_l520_0049c38a()
{
	char pad[520]; gen_uw_sink(pad);
	Gen_uw_0049c38a v; gen_uw_ext();
}

void gen_uw_l560_0049c38a()
{
	char pad[560]; gen_uw_sink(pad);
	Gen_uw_0049c38a v; gen_uw_ext();
}

void gen_uw_l624_0049c38a()
{
	char pad[624]; gen_uw_sink(pad);
	Gen_uw_0049c38a v; gen_uw_ext();
}

void gen_uw_l688_0049c38a()
{
	char pad[688]; gen_uw_sink(pad);
	Gen_uw_0049c38a v; gen_uw_ext();
}

void gen_uw_l4_004c9f38()
{
	Gen_uw_004c9f38 v0; gen_uw_ext();
	Gen_uw_004c9f38 v1; gen_uw_ext();
}

void gen_uw_l8_004c9f38()
{
	char pad[8]; gen_uw_sink(pad);
	Gen_uw_004c9f38 v; gen_uw_ext();
}

void gen_uw_l12_004c9f38()
{
	char pad[12]; gen_uw_sink(pad);
	Gen_uw_004c9f38 v; gen_uw_ext();
}

void gen_uw_l16_004c9f38()
{
	char pad[16]; gen_uw_sink(pad);
	Gen_uw_004c9f38 v; gen_uw_ext();
}

void gen_uw_l20_004c9f38()
{
	char pad[20]; gen_uw_sink(pad);
	Gen_uw_004c9f38 v; gen_uw_ext();
}

void gen_uw_l24_004c9f38()
{
	char pad[24]; gen_uw_sink(pad);
	Gen_uw_004c9f38 v; gen_uw_ext();
}

void gen_uw_l28_004c9f38()
{
	char pad[28]; gen_uw_sink(pad);
	Gen_uw_004c9f38 v; gen_uw_ext();
}

void gen_uw_l36_004c9f38()
{
	char pad[36]; gen_uw_sink(pad);
	Gen_uw_004c9f38 v; gen_uw_ext();
}

void gen_uw_l40_004c9f38()
{
	char pad[40]; gen_uw_sink(pad);
	Gen_uw_004c9f38 v; gen_uw_ext();
}

void gen_uw_l52_004c9f38()
{
	char pad[52]; gen_uw_sink(pad);
	Gen_uw_004c9f38 v; gen_uw_ext();
}

void gen_uw_l60_004c9f38()
{
	char pad[60]; gen_uw_sink(pad);
	Gen_uw_004c9f38 v; gen_uw_ext();
}

void gen_uw_l68_004c9f38()
{
	char pad[68]; gen_uw_sink(pad);
	Gen_uw_004c9f38 v; gen_uw_ext();
}

void gen_uw_l84_004c9f38()
{
	char pad[84]; gen_uw_sink(pad);
	Gen_uw_004c9f38 v; gen_uw_ext();
}

void gen_uw_l136_004c9f38()
{
	char pad[136]; gen_uw_sink(pad);
	Gen_uw_004c9f38 v; gen_uw_ext();
}

void gen_uw_l328_004c9f38()
{
	char pad[328]; gen_uw_sink(pad);
	Gen_uw_004c9f38 v; gen_uw_ext();
}

void gen_uw_l336_004c9f38()
{
	char pad[336]; gen_uw_sink(pad);
	Gen_uw_004c9f38 v; gen_uw_ext();
}

void gen_uw_l344_004c9f38()
{
	char pad[344]; gen_uw_sink(pad);
	Gen_uw_004c9f38 v; gen_uw_ext();
}

void gen_uw_l352_004c9f38()
{
	char pad[352]; gen_uw_sink(pad);
	Gen_uw_004c9f38 v; gen_uw_ext();
}

void gen_uw_l360_004c9f38()
{
	char pad[360]; gen_uw_sink(pad);
	Gen_uw_004c9f38 v; gen_uw_ext();
}

void gen_uw_l368_004c9f38()
{
	char pad[368]; gen_uw_sink(pad);
	Gen_uw_004c9f38 v; gen_uw_ext();
}

void gen_uw_l376_004c9f38()
{
	char pad[376]; gen_uw_sink(pad);
	Gen_uw_004c9f38 v; gen_uw_ext();
}

void gen_uw_l384_004c9f38()
{
	char pad[384]; gen_uw_sink(pad);
	Gen_uw_004c9f38 v; gen_uw_ext();
}

void gen_uw_l392_004c9f38()
{
	char pad[392]; gen_uw_sink(pad);
	Gen_uw_004c9f38 v; gen_uw_ext();
}

void gen_uw_l400_004c9f38()
{
	char pad[400]; gen_uw_sink(pad);
	Gen_uw_004c9f38 v; gen_uw_ext();
}

void gen_uw_l408_004c9f38()
{
	char pad[408]; gen_uw_sink(pad);
	Gen_uw_004c9f38 v; gen_uw_ext();
}

void gen_uw_l416_004c9f38()
{
	char pad[416]; gen_uw_sink(pad);
	Gen_uw_004c9f38 v; gen_uw_ext();
}

void gen_uw_l424_004c9f38()
{
	char pad[424]; gen_uw_sink(pad);
	Gen_uw_004c9f38 v; gen_uw_ext();
}

void gen_uw_l432_004c9f38()
{
	char pad[432]; gen_uw_sink(pad);
	Gen_uw_004c9f38 v; gen_uw_ext();
}

void gen_uw_l672_004cacb8()
{
	char pad[672]; gen_uw_sink(pad);
	Gen_uw_004cacb8 v; gen_uw_ext();
}

void gen_uw_l36_004e1416()
{
	char pad[36]; gen_uw_sink(pad);
	Gen_uw_004e1416 v; gen_uw_ext();
}

void gen_uw_l20_004e14e1()
{
	char pad[20]; gen_uw_sink(pad);
	Gen_uw_004e14e1 v; gen_uw_ext();
}

void gen_uw_l4_004e156b()
{
	Gen_uw_004e156b v0; gen_uw_ext();
	Gen_uw_004e156b v1; gen_uw_ext();
}

void gen_uw_l20_004e18a2()
{
	char pad[20]; gen_uw_sink(pad);
	Gen_uw_004e18a2 v; gen_uw_ext();
}

void gen_uw_l24_004e194e()
{
	char pad[24]; gen_uw_sink(pad);
	Gen_uw_004e194e v; gen_uw_ext();
}

void gen_uw_l16_004e1b72()
{
	char pad[16]; gen_uw_sink(pad);
	Gen_uw_004e1b72 v; gen_uw_ext();
}

void gen_uw_l28_004e32f2()
{
	char pad[28]; gen_uw_sink(pad);
	Gen_uw_004e32f2 v; gen_uw_ext();
}

void gen_uw_l36_004f5115()
{
	char pad[36]; gen_uw_sink(pad);
	Gen_uw_004f5115 v; gen_uw_ext();
}

void gen_uw_l40_004f5115()
{
	char pad[40]; gen_uw_sink(pad);
	Gen_uw_004f5115 v; gen_uw_ext();
}

void gen_uw_l16_0050c283()
{
	char pad[16]; gen_uw_sink(pad);
	Gen_uw_0050c283 v; gen_uw_ext();
}

void gen_uw_l44_0050c283()
{
	char pad[44]; gen_uw_sink(pad);
	Gen_uw_0050c283 v; gen_uw_ext();
}

void gen_uw_l116_0050c283()
{
	char pad[116]; gen_uw_sink(pad);
	Gen_uw_0050c283 v; gen_uw_ext();
}

void gen_uw_l192_0050c4e8()
{
	char pad[192]; gen_uw_sink(pad);
	Gen_uw_0050c4e8 v; gen_uw_ext();
}

void gen_uw_l4_0052af77()
{
	Gen_uw_0052af77 v0; gen_uw_ext();
	Gen_uw_0052af77 v1; gen_uw_ext();
}

void gen_uw_l16_00535776()
{
	char pad[16]; gen_uw_sink(pad);
	Gen_uw_00535776 v; gen_uw_ext();
}

void gen_uw_l24_00535776()
{
	char pad[24]; gen_uw_sink(pad);
	Gen_uw_00535776 v; gen_uw_ext();
}

void gen_uw_l28_00535776()
{
	char pad[28]; gen_uw_sink(pad);
	Gen_uw_00535776 v; gen_uw_ext();
}

void gen_uw_l36_00535776()
{
	char pad[36]; gen_uw_sink(pad);
	Gen_uw_00535776 v; gen_uw_ext();
}

void gen_uw_l112_00535776()
{
	char pad[112]; gen_uw_sink(pad);
	Gen_uw_00535776 v; gen_uw_ext();
}

void gen_uw_l132_00535776()
{
	char pad[132]; gen_uw_sink(pad);
	Gen_uw_00535776 v; gen_uw_ext();
}

void gen_uw_l28_0054f508()
{
	char pad[28]; gen_uw_sink(pad);
	Gen_uw_0054f508 v; gen_uw_ext();
}

void gen_uw_l860_0054f508()
{
	char pad[860]; gen_uw_sink(pad);
	Gen_uw_0054f508 v; gen_uw_ext();
}

void gen_uw_l16_005596ea()
{
	char pad[16]; gen_uw_sink(pad);
	Gen_uw_005596ea v; gen_uw_ext();
}

void gen_uw_l20_005596ea()
{
	char pad[20]; gen_uw_sink(pad);
	Gen_uw_005596ea v; gen_uw_ext();
}

void gen_uw_l28_005596ea()
{
	char pad[28]; gen_uw_sink(pad);
	Gen_uw_005596ea v; gen_uw_ext();
}

void gen_uw_l32_005596ea()
{
	char pad[32]; gen_uw_sink(pad);
	Gen_uw_005596ea v; gen_uw_ext();
}

void gen_uw_l80_005596ea()
{
	char pad[80]; gen_uw_sink(pad);
	Gen_uw_005596ea v; gen_uw_ext();
}

void gen_uw_l100_0055a614()
{
	char pad[100]; gen_uw_sink(pad);
	Gen_uw_0055a614 v; gen_uw_ext();
}

void gen_uw_l8_00577998()
{
	char pad[8]; gen_uw_sink(pad);
	Gen_uw_00577998 v; gen_uw_ext();
}

void gen_uw_l16_00577998()
{
	char pad[16]; gen_uw_sink(pad);
	Gen_uw_00577998 v; gen_uw_ext();
}

void gen_uw_l24_00577998()
{
	char pad[24]; gen_uw_sink(pad);
	Gen_uw_00577998 v; gen_uw_ext();
}

void gen_uw_l32_00577998()
{
	char pad[32]; gen_uw_sink(pad);
	Gen_uw_00577998 v; gen_uw_ext();
}

void gen_uw_l188_00577998()
{
	char pad[188]; gen_uw_sink(pad);
	Gen_uw_00577998 v; gen_uw_ext();
}

void gen_uw_l0_005b804e()
{
	Gen_uw_005b804e v; gen_uw_ext();
}

void gen_uw_l4_005b804e()
{
	Gen_uw_005b804e v0; gen_uw_ext();
	Gen_uw_005b804e v1; gen_uw_ext();
}

void gen_uw_l8_005b804e()
{
	char pad[8]; gen_uw_sink(pad);
	Gen_uw_005b804e v; gen_uw_ext();
}

void gen_uw_l12_005b804e()
{
	char pad[12]; gen_uw_sink(pad);
	Gen_uw_005b804e v; gen_uw_ext();
}

void gen_uw_l16_005b804e()
{
	char pad[16]; gen_uw_sink(pad);
	Gen_uw_005b804e v; gen_uw_ext();
}

void gen_uw_l20_005b804e()
{
	char pad[20]; gen_uw_sink(pad);
	Gen_uw_005b804e v; gen_uw_ext();
}
