// cl: /O1 /DNDEBUG /MD /arch:SSE /EHsc /Ireference/shims/bfme2_ascii /Ireference/shims/moduledata /ICode/GameEngine/Include
// TU Code/GameEngine/Source/GameLogic/Object/Behavior/RebuildHoleBehavior.cpp: generated by tools/tu_skeleton.py from tu_map.csv (approved rows, retail order)
#pragma comment(linker, "/alternatename:_vtbl_00C078DC=??_7BfmeCtor001B3A20@@6BBfmeCtorVirtualBase001B3A20@@@")
#pragma comment(linker, "/alternatename:_vtbl_00C1C780=??_7?$CategoryModuleInfo@$00@FXParticleSystem@@6B@")

// ?getRebuildHoleBehaviorInterfaceFromObject@RebuildHoleBehavior@@SAPAVRebuildHoleBehaviorInterface@@PAVObject@@@Z @0x004831CB 115B. Static RebuildHoleBehavior
// NameKey plus behavior-module scan at +0x244 via slot 0x10 tag compare, returns module+0x24.
// Evidence: "RebuildHoleBehavior" literal with TheNameKeyGenerator row 0x00148E1A; callers
// 0x0031C0EE 0x00486908 0x00507017; ZH donor RebuildHoleBehavior.cpp getRebuildHoleBehaviorInterfaceFromObject
// loops getBehaviorModules; BFME2 uses NameKey tag at slot 0x10 per retail.
enum NameKeyType
{
	NAMEKEY_INVALID = 0
};

class NameKeyGenerator
{
public:
	NameKeyType nameToKey(const char *name);
};

extern NameKeyGenerator *TheNameKeyGenerator;

class RebuildHoleBehaviorInterface
{
public:
	virtual void dummy() = 0;
};

class BehaviorModule
{
public:
	virtual void s00() = 0;
	virtual void s04() = 0;
	virtual void s08() = 0;
	virtual void s0C() = 0;
	virtual NameKeyType getModuleTag() = 0;
};

class Object
{
public:
	BehaviorModule **getBehaviorModules() { return m_behaviorModules; }

private:
	char m_pad[0x244];
	BehaviorModule **m_behaviorModules;
};

//
// ??0RebuildHoleBehaviorModuleData@@QAE@XZ,
// retail 0x0048323E, 34 bytes. Frameless ModuleData ctor: the vtable literal
// 0x00C49950 stays an explicit first member (no virtuals declared, so no
// vtable is emitted and no dtor row is owed), the +0x04 word retail never
// stores, WorkerRespawnDelay at +0x08 zeroed via xorps/movss, HoleHealth at
// +0x0C from the shared 0.1f global, and WorkerObjectName at +0x10 cleared.
// Field identity is retail's own INI table at 0x00C49A10 (landed
// buildFieldParse row: WorkerObjectName plus WorkerRespawnDelay plus
// HoleHealthRegen%PerSecond) beside the rowed RebuildHoleBehavior pool key
// (0x4832D7); the 0x24C433 factory sole-calls this ctor. The holeName
// pointer anchors the and-zero below the vtable store (RebuildHoleExposeDie
// precedent: else it hoists above it); the temp splits the global load above
// the vtable store (else the health store sinks below it).

#include "Common/BfmeModuleData.h"

// Vtable 0x00C49950: slot 0 the rowed deleting dtor 0x0048332E over the rowed
// dtor 0x0048334A, slots 1-30 the shared ModuleData bodies.
class RebuildHoleBehaviorModuleData : public ModuleData
{
public:
	RebuildHoleBehaviorModuleData();
	virtual ~RebuildHoleBehaviorModuleData();

private:
	unsigned int m_unused04;
	float m_workerRespawnDelay;	// +0x08
	float m_holeHealthRegen;	// +0x0C
	int m_workerObjectName;		// +0x10 (name key data word)
};

//
// ??0RebuildHoleBehavior@@QAE@PAVThing@@PBVModuleData@@@Z, retail 0x00483271,
// 102 bytes. RebuildHoleBehavior ctor over the rowed UpdateModule base
// (0x253390, thing plus data). FakePathfindPortalBehaviour two-phase idiom:
// sourced-before address-take slots commit the initial +0x20/+0x24 constants
// first; a shared-zero run clears +0x28 through +0x3C; the vtable group
// reinstalls the primary slot, the +0x0C/+0x10 secondaries and +0x20/+0x24;
// a float zero lands at +0x40 and a set flag at +0x44 (address-of TU-local
// dummies, DIR32-masked; no virtuals are declared anywhere so no vtable is
// emitted here).
//
// The rowed name getter at 0x48331C (RebuildHoleBehavior literal), the pool
// key at 0x4832D7, the ModuleData pair (ctor 0x48323E plus factory 0x24C433)
// and the rowed instance factory 0x24C3FB (sole caller, ModuleFactory
// registration literal) prove the class. Row supersedes the ctor pin.

extern "C" const void *const vtbl_00C078DC[];

extern "C" const void *const vtbl_00C1C780[];

class Thing;

class ModuleData;

static int s_vtable;

static int s_secondary0C;

static int s_secondary10;

static int s_secondary20;

static int s_secondary24;

// Opaque UpdateModule base; ctor resolves to its row. The explicit m_vtable
// member stands in for the inherited vptr so body order is source order.
class UpdateModule
{
public:
	UpdateModule(Thing *thing, const ModuleData *moduleData);

protected:
	const void *m_vtable;
	Thing *m_owner;
	int m_pad08;
	const void *m_p0C;
	const void *m_p10;
	unsigned char m_pad[0x20 - 0x14];
};

class RebuildHoleBehavior : public UpdateModule
{
public:
	RebuildHoleBehavior(Thing *thing, const ModuleData *moduleData);
private:
	const void *m_secondary20;
private:
	const void *m_secondary24;
private:
	int m_28;
private:
	int m_2C;
private:
	int m_30;
private:
	int m_34;
private:
	int m_38;
private:
	int m_3C;
private:
	float m_40;
private:
	bool m_44;
public:
	static RebuildHoleBehaviorInterface *getRebuildHoleBehaviorInterfaceFromObject(Object *obj);
};

// ---- from Code/GameEngine/Source/GameLogic/Object/Behavior/RebuildHoleBehaviorGetInterface.cpp

RebuildHoleBehaviorInterface *RebuildHoleBehavior::getRebuildHoleBehaviorInterfaceFromObject(Object *obj)
{
	static NameKeyType key = TheNameKeyGenerator->nameToKey("RebuildHoleBehavior");
	for (BehaviorModule **i = obj->getBehaviorModules(); *i; ++i)
	{
		if ((*i)->getModuleTag() == key)
		{
			BehaviorModule *m = *i;
			if (m)
				return (RebuildHoleBehaviorInterface *)((char *)m + 0x24);
			return 0;
		}
	}
	return 0;
}

// ---- from Code/GameEngine/Source/GameLogic/Object/Behavior/RebuildHoleBehaviorModuleDataCtor.cpp

// ??0RebuildHoleBehaviorModuleData@@QAE@XZ @0x48323E
RebuildHoleBehaviorModuleData::RebuildHoleBehaviorModuleData()
{
	int *workerName = &m_workerObjectName;
	m_workerRespawnDelay = 0.0f;
	m_holeHealthRegen = 0.1f;
	*workerName &= 0;
}

// tu-skeleton: 0x00483260 17B ?buildFieldParse@RebuildHoleBehaviorModuleData@@SAXAAVMultiIniFieldParse@@@Z -- matched in Code/GameEngine/Source/GameLogic/Object/Update/ModuleDataBuildFieldParse.cpp (not merged yet)

// ---- from Code/GameEngine/Source/GameLogic/Object/Behavior/RebuildHoleBehaviorCtor.cpp

  // folded, 4 classes; via ??_7BfmeCtor001B3A20@@6BBfmeCtorVirtualBase001B3A20@@@

  // folded, 49 classes; via ??_7?$CategoryModuleInfo@$00@FXParticleSystem@@6B@

// ??0RebuildHoleBehavior@@QAE@PAVThing@@PBVModuleData@@@Z @0x483271
RebuildHoleBehavior::RebuildHoleBehavior(Thing *thing, const ModuleData *moduleData)
	: UpdateModule(thing, moduleData)
{
	int *slot20 = (int *)&m_secondary20;
	*slot20 = (int)((unsigned int)vtbl_00C1C780);
	int *slot24 = (int *)&m_secondary24;
	*slot24 = (int)((unsigned int)vtbl_00C078DC);
	m_28 = 0;
	m_2C = 0;
	m_30 = 0;
	m_34 = 0;
	m_38 = 0;
	m_3C = 0;
	m_vtable = &s_vtable;
	m_p0C = &s_secondary0C;
	m_p10 = &s_secondary10;
	m_secondary20 = &s_secondary20;
	m_secondary24 = &s_secondary24;
	m_40 = 0.0f;
	m_44 = true;
}

// tu-skeleton: 0x004832D7 69B ?rva0004832D7@RebuildHoleBehavior@@SA?AW4NameKeyType@@XZ -- matched in Code/GameEngine/Source/GameLogic/Object/Behavior/RebuildHoleBehaviorPoolKey.cpp (not merged yet)

// tu-skeleton: 0x0048331C 6B ?name@Rva0048331CNamed@@QBEPBDXZ -- matched in Code/GameEngine/Source/Common/ModuleNameGetters.cpp (not merged yet)

// tu-skeleton: 0x0048332E 28B ??_GRebuildHoleBehaviorModuleData@@UAEPAXI@Z -- matched in Code/GameEngine/Source/GameLogic/Object/Behavior/BehaviorModuleDeletingDtors.cpp (not merged yet)

// tu-skeleton: 0x0048334A 48B ??1RebuildHoleBehaviorModuleData@@UAE@XZ -- matched in Code/GameEngine/Source/GameLogic/Object/Behavior/RebuildHoleBehaviorModuleDataDtor.cpp (not merged yet)

// tu-skeleton: 0x0048337A 114B ?newWorkerRespawnProcess@RebuildHoleBehavior@@QAEXPAVObject@@@Z -- matched in Code/GameEngine/Source/GameLogic/Object/Behavior/RebuildHoleBehaviorPoolKey.cpp (not merged yet)

// tu-skeleton: 0x004833EC 338B ?xfer@RebuildHoleBehavior@@MAEXPAVXfer@@@Z -- matched in Code/GameEngine/Source/GameLogic/Object/Behavior/RebuildHoleBehaviorXfer.cpp (not merged yet)

// tu-skeleton: 0x0048353E 118B ??1RebuildHoleBehavior@@UAE@XZ -- matched in Code/GameEngine/Source/GameLogic/Object/Behavior/RebuildHoleBehaviorDtor.cpp (not merged yet)

// tu-skeleton: 0x004835FB 46B ?rva004835FB@Rva004835FB@@QAEXH@Z -- matched in Code/GameEngine/Source/Common/VslotSmallBodiesW.cpp (not merged yet)

// tu-skeleton: 0x00483629 28B ??_GRebuildHoleBehavior@@UAEPAXI@Z -- matched in Code/GameEngine/Source/GameLogic/Object/Behavior/RebuildHoleBehaviorDtor.cpp (not merged yet)
