// ?rva0046FA46@HordeContain@@UAEXPAVObject@@H@Z
// Native 0x0046FA46..0x0046FC1B (469B), RET8, C44EC8 interface slot22.
// Owner identity: named HordeContain ctor/vtables and same-family callbacks.
// Target facts: status38, producer/rider notification, ID map, virtual
// placement/orientation, terrain layer, AI and drawable propagation below.
// Layout offsets are retail accesses, not carried as donor facts.
// The original method name remains unknown. Helper 46E6EA takes an opaque
// third pointer here containing the owner Object; retain the existing ABI
// spelling without asserting that its pointee is a coordinate at this call.
// Same-valued owner-conditioned AI PHI keeps the native ECX load. Declaring
// zero angle before the iface pointer gives the native order of stack stores.
// cl: /O1 /G7 /arch:SSE /Oy- /DNDEBUG /MD /ICode/Libraries/Include /Ireference/shims/bfmealloc /D_STLP_USE_STATIC_LIB /D_CRTIMP=
// stlport
#include "Lib/Coord3D.h"
#include <map>

// map/set<int> internals otherwise instantiate the less<int>::operator()
// COMDAT (one byte shape per TU flags); an explicit dllimport+forceinline
// specialization takes those calls inline so this TU emits no external copy.
namespace _STL {
template <> __declspec(dllimport) __forceinline
bool less<int>::operator()(const int &a, const int &b) const
{ return a < b; }
}
class Object; class Drawable;
enum ObjectStatusTypes {RvaStatus38=38};
class Thing {public:void setPosition(const Coord3D*);void setOrientation(float);};
class Object:public Thing {public:
 char p000[0x38];Coord3D position;float angle;
 char p048[0x74-0x48];int id;
 char p078[0x258-0x78];void*ai;
 void setStatus(ObjectStatusTypes,bool);void setProducer(Object*);
 int rva0028F4EF();void rva0029130C(int);Drawable*getDrawable()const;
};
class Drawable {public:char p000[0x43c];bool flag43c;void rva00272945(int);void rva00272BAB(int,int);};
class Rva0028B525DwordSlot {public:void set(int);};
class Rva00463097 {public:void rva00463097(int,int);};
struct Rva0046E6EAObject;struct Rva0046E6EACoord;
class Rva0046E6EA {public:bool rva0046E6EA(Rva0046E6EAObject*,const Rva0046E6EACoord*,Rva0046E6EACoord*,bool);};
class Pathfinder {public:int GetGroundLayer(const Coord3D*);};
class AI {public:char p00[0x10];Pathfinder*pathfinder;};extern AI*TheAI;
class GlobalData;extern GlobalData*TheWritableGlobalData;
struct RvaGlobalData9A6 {char p[0x9a6];bool flag;};
class RvaTerrain {public:
virtual void t0();
virtual void t1();
virtual void t2();
virtual void t3();
virtual void t4();
virtual void t5();
virtual void t6();
virtual float height(float,float,int,void*,bool);};
class TerrainLogic;extern TerrainLogic*TheTerrainLogic;
class RvaHordeIface11C {public:
virtual void h0();
virtual void h1();
virtual void h2();
virtual void h3();
virtual void h4();
virtual void h5();
virtual void h6();
virtual Coord3D position(Object*,float*);
virtual void h8();
virtual void h9();
virtual void h10();
virtual void h11();
virtual void h12();
virtual void h13();
virtual void h14();
virtual void h15();
virtual void h16();
virtual void h17();
virtual void h18();
virtual void h19();
virtual void h20();
virtual void h21();
virtual void h22();
virtual void h23();
virtual void h24();
virtual void h25();
virtual void h26();
virtual void h27();
virtual void h28();
virtual void h29();
virtual void h30();
virtual void h31();
virtual void h32();
virtual void h33();
virtual void h34();
virtual void h35();
virtual void h36();
virtual void h37();
virtual void h38();
virtual void h39();
virtual void h40();
virtual void h41();
virtual void h42();
virtual void h43();
virtual void h44();
virtual void h45();
virtual void h46();
virtual void h47();
virtual void h48();
virtual void h49();
virtual void h50();
virtual void h51();
virtual void h52();
virtual void h53();
virtual void h54();
virtual void h55();
virtual void h56();
virtual void h57();
virtual void h58();
virtual void h59();
virtual void h60();
virtual void h61();
virtual void h62();
virtual void h63();
virtual void h64();
virtual void h65();
virtual void h66();
virtual void h67();
virtual void h68();
virtual void h69();
virtual void h70();
virtual void h71();
virtual void h72();
virtual void h73();
virtual void h74();
virtual void h75();
virtual void h76();
virtual void h77();
virtual void h78();
virtual void h79();
virtual void h80();
virtual void h81();
virtual void h82();
virtual void h83();
virtual void h84();
virtual void h85();
virtual void h86();
virtual void h87();
virtual void h88();
virtual void h89();
virtual void h90();
virtual void h91();
virtual void h92();
virtual void h93();
virtual void h94();
virtual void h95();
virtual int key(bool);
virtual void h97();
virtual void h98();
virtual void h99();
virtual void h100();
virtual int keyFor(Object*);};
class RvaObjectAI {public:
virtual void a0();
virtual void a1();
virtual void a2();
virtual void a3();
virtual void a4();
virtual void a5();
virtual void a6();
virtual void a7();
virtual void a8();
virtual void a9();
virtual void a10();
virtual void a11();
virtual void a12();
virtual void a13();
virtual void a14();
virtual void a15();
virtual void a16();
virtual void a17();
virtual void a18();
virtual void a19();
virtual void a20();
virtual void a21();
virtual void a22();
virtual void a23();
virtual void a24();
virtual void a25();
virtual void a26();
virtual void a27();
virtual void a28();
virtual void a29();
virtual void a30();
virtual void a31();
virtual void a32();
virtual void a33();
virtual void a34();
virtual void a35();
virtual void a36();
virtual void a37();
virtual void a38();
virtual void a39();
virtual void a40();
virtual void a41();
virtual void a42();
virtual void a43();
virtual void a44();
virtual void a45();
virtual void a46();
virtual void a47();
virtual void a48();
virtual void a49();
virtual void a50();
virtual void a51();
virtual void a52();
virtual void a53();
virtual void a54();
virtual void a55();
virtual void a56();
virtual void a57();
virtual void a58();
virtual void a59();
virtual void a60();
virtual void a61();
virtual void a62();
virtual void a63();
virtual void a64();
virtual void a65();
virtual void a66();
virtual void a67();
virtual void a68();
virtual void a69();
virtual void a70();
virtual void a71();
virtual void a72();
virtual void a73();
virtual void a74();
virtual void a75();
virtual void a76();
virtual void a77();
virtual void a78();
virtual void a79();
virtual void a80();
virtual void a81();
virtual void a82();
virtual void a83();
virtual void a84();
virtual void a85();
virtual void a86();
virtual void a87();
virtual void a88();
virtual void a89();
virtual void a90();
virtual void a91();
virtual void a92();
virtual void a93();
virtual void a94();
virtual void a95();
virtual void a96();
virtual void a97();
virtual void a98();
virtual void a99();
virtual void a100();
virtual void a101();
virtual void a102();
virtual void a103();
virtual void a104();
virtual void a105();
virtual void a106();
virtual void a107();
virtual void a108();
virtual void a109();
virtual void a110();
virtual void a111();
virtual void a112();
virtual void a113();
virtual void a114();
virtual void a115();
virtual void a116();
virtual void a117();
virtual void a118();
virtual void a119();
virtual void a120();
virtual void a121();
virtual void a122();
virtual void a123();
virtual void a124();
virtual void a125();
virtual void a126();
virtual void a127();
virtual void a128();
virtual void a129();
virtual void a130();
virtual void a131();
virtual void a132();
virtual void a133();
virtual void a134();
virtual void a135();
virtual void a136();
virtual void a137();
virtual void a138();
virtual void a139();
virtual void a140();
virtual void a141();
virtual void a142(int);};
struct RvaHordeData {char p000[0x234];int value234;};
class RvaHordePrimary {public:
virtual void p0();
virtual void p1();
virtual void p2();
virtual void p3();
virtual void p4();
virtual void p5();
virtual void p6();
virtual void p7();
virtual void p8();
virtual void p9();
virtual void p10();
virtual void p11();
virtual void p12();
virtual void p13();
virtual void p14();
virtual void p15();
virtual void p16();
virtual void p17();
virtual void p18();
virtual void p19();
virtual void p20();
virtual void p21();
virtual void p22();
virtual void p23();
virtual void p24();
virtual void p25();
virtual void p26();
virtual void p27();
virtual void p28();
virtual void p29();
virtual void p30();
virtual void p31();
virtual void p32();
virtual void p33(bool);virtual void p34();
 RvaHordeData*data;Object*owner;char p0C[0x20-0xC];
};
class RvaHordeContainIface {public:
virtual void c0();
virtual void c1();
virtual void c2();
virtual void c3();
virtual void c4();
virtual void c5();
virtual void c6();
virtual void c7();
virtual void c8();
virtual void c9();
virtual void c10();
virtual void c11();
virtual void c12();
virtual void c13();
virtual void c14();
virtual void c15();
virtual void c16();
virtual void c17();
virtual void c18();
virtual void c19();
virtual void c20();
virtual void c21();
virtual void rva0046FA46(Object*,int);
};
class HordeContain:public RvaHordePrimary,public RvaHordeContainIface {
public:virtual void rva0046FA46(Object*,int);void rva0046A893(Object*);
 char p024[0x120-0x24];bool flag120;
 char p121[0x17C-0x121];_STL::map<int,int> ids;
 char p188[0x198-(0x17C+sizeof(_STL::map<int,int>))];bool flag198;
};
void HordeContain::rva0046FA46(Object*object,int arg){
 object->setStatus(RvaStatus38,true);
 reinterpret_cast<Rva00463097*>(reinterpret_cast<char*>(this)+0x20)->rva00463097(reinterpret_cast<int>(object),arg);
 object->setProducer(owner);
 flag120=true;rva0046A893(object);
 object->rva0029130C(owner->rva0028F4EF());
 int id=object->id;
 if(ids.find(id)!=ids.end())return;
 if(!flag198)p33(true);
 p34();
 float angle=0.0f;
 RvaHordeIface11C*h=reinterpret_cast<RvaHordeIface11C*>(reinterpret_cast<char*>(this)+0x11C);
 Coord3D pos=h->position(object,&angle);
 int layer=(owner?TheAI:TheAI)->pathfinder->GetGroundLayer(&owner->position);
 reinterpret_cast<Rva0046E6EA*>(this)->rva0046E6EA(reinterpret_cast<Rva0046E6EAObject*>(object),reinterpret_cast<const Rva0046E6EACoord*>(&pos),reinterpret_cast<Rva0046E6EACoord*>(owner),false);
 pos.z=reinterpret_cast<RvaTerrain*>(TheTerrainLogic)->height(pos.x,pos.y,layer,0,true);
 object->setPosition(&pos);object->setPosition(&pos);
 reinterpret_cast<Rva0028B525DwordSlot*>(object)->set(layer);
 if(angle==0.0f)object->setOrientation(owner->angle);else object->setOrientation(angle);
 if(data){int value=data->value234;if(value!=-1){RvaObjectAI*ai=static_cast<RvaObjectAI*>(object->ai);if(ai)ai->a142(value);}}
 Object*self=owner;
 if(self){Drawable*draw=self->getDrawable();
  if(draw && draw->flag43c){
   if(reinterpret_cast<RvaGlobalData9A6*>(TheWritableGlobalData)->flag)draw->rva00272945(h->key(false));
   else {Drawable*child=object->getDrawable();if(child)child->rva00272BAB(1,h->keyFor(self));}
  }
 }
}
