// cl: /O1 /G7 /DNDEBUG /MD /arch:SSE
// ?rva0047676B@HorseHordeContain@@UAE_NM@Z @0x0047676B 163B
// Evidence: Native47676B..47680E RET4 primary neighbour HorseHordeContain. Receiver adjusted-FC to containment interface and virtual118 outputs8B range; float maxTurn from independently rowed holder28AC4E andLocomotor1E3E9F; orientation44 inline getter yields native dualSSE loads; normalizeAngle238954/fabs629210 and native x87 greater comparison. Original virtual method name remains unknown.
#include <math.h>
float normalizeAngle(float);
class Object;
struct Rva0028AC4EEntry;
class Locomotor {public:float getMaxTurnRate(Object*)const;};
class Object {public:const Rva0028AC4EEntry*rva0028AC4E()const;char pad[0x44];float angle;float getOrientation()const{return angle;}};
struct Rva0046247DPair {void*a;void*b;};
class ContainView {public:virtual void d0();
virtual void d1();
virtual void d2();
virtual void d3();
virtual void d4();
virtual void d5();
virtual void d6();
virtual void d7();
virtual void d8();
virtual void d9();
virtual void d10();
virtual void d11();
virtual void d12();
virtual void d13();
virtual void d14();
virtual void d15();
virtual void d16();
virtual void d17();
virtual void d18();
virtual void d19();
virtual void d20();
virtual void d21();
virtual void d22();
virtual void d23();
virtual void d24();
virtual void d25();
virtual void d26();
virtual void d27();
virtual void d28();
virtual void d29();
virtual void d30();
virtual void d31();
virtual void d32();
virtual void d33();
virtual void d34();
virtual void d35();
virtual void d36();
virtual void d37();
virtual void d38();
virtual void d39();
virtual void d40();
virtual void d41();
virtual void d42();
virtual void d43();
virtual void d44();
virtual void d45();
virtual void d46();
virtual void d47();
virtual void d48();
virtual void d49();
virtual void d50();
virtual void d51();
virtual void d52();
virtual void d53();
virtual void d54();
virtual void d55();
virtual void d56();
virtual void d57();
virtual void d58();
virtual void d59();
virtual void d60();
virtual void d61();
virtual void d62();
virtual void d63();
virtual void d64();
virtual void d65();
virtual void d66();
virtual void d67();
virtual void d68();
virtual void d69(); virtual void items(Rva0046247DPair&);};
struct Node {Node*next;Node*prev;Object*object;};
class HorseHordeContain {public:virtual bool rva0047676B(float);};
bool HorseHordeContain::rva0047676B(float angle){
 Rva0046247DPair pair;
 reinterpret_cast<ContainView*>(reinterpret_cast<char*>(this)-0xFC)->items(pair);
 Node*n=(*static_cast<Node**>(pair.b))->next;
 float maxTurn=0.0f;
 for(;n!=*static_cast<Node**>(pair.b);n=n->next){
  Object*o=n->object;
  if(maxTurn==0.0f && o->rva0028AC4E())maxTurn=reinterpret_cast<const Locomotor*>(o->rva0028AC4E())->getMaxTurnRate(o);
  if(fabs(normalizeAngle(angle-o->getOrientation()))>maxTurn)return false;
 }
 return true;
}
